// ═══════════════════════════════════════════════════════════════════
// BANCO DE PREGUNTAS — Despliegue de Aplicaciones Web (0614)
// Basado en temario UAX + cuestionarios oficiales UF1–UF5
// ═══════════════════════════════════════════════════════════════════

const BANCO = {

  // ─────────────────────────────────────────────────────────
  // UF1 — SERVICIOS DE RED IMPLICADOS EN EL DESPLIEGUE
  // DNS · LDAP · Cloud · Contenedores
  // ─────────────────────────────────────────────────────────
  UF1: [
    { tema:'UF1', p:'¿Qué tecnología es fundamental para el despliegue de contenedores?', ops:['Los balanceadores de carga','La virtualización','Los firewalls','Los proxies inversos'], r:1, e:'La virtualización es la tecnología base que hace posible los contenedores: permite ejecutar entornos aislados sobre el mismo hardware físico.' },
    { tema:'UF1', p:'En DNS, ¿qué es un dominio de nivel superior (TLD)?', ops:['El primer servidor DNS en la jerarquía','Un registro que apunta a un servidor de correo','El último segmento de un nombre de dominio','El servidor autoritativo de una zona'], r:2, e:'TLD = Top Level Domain. Es el último segmento del nombre de dominio: .com, .es, .org, etc. Están gestionados por la ICANN.' },
    { tema:'UF1', p:'¿Qué tipo de alojamiento web utiliza recursos de múltiples servidores para equilibrar la carga y maximizar la disponibilidad?', ops:['Alojamiento dedicado','Alojamiento VPS','Alojamiento en la nube','Alojamiento compartido'], r:2, e:'El cloud hosting distribuye la carga entre múltiples servidores. Si uno falla, otros asumen la carga. Ofrece alta disponibilidad y escalabilidad elástica.' },
    { tema:'UF1', p:'¿Cómo afecta el alojamiento en la nube a la escalabilidad de una aplicación web?', ops:['Reduce la capacidad de escalar','No tiene impacto en la escalabilidad','Requiere intervención manual para cada cambio','Facilita el escalado rápido y eficiente de recursos'], r:3, e:'El cloud permite escalar vertical u horizontalmente de forma casi inmediata, sin necesidad de adquirir hardware físico nuevo.' },
    { tema:'UF1', p:'¿Cuál es la ventaja principal del despliegue de contenedores?', ops:['El aumento de la seguridad cibernética','La reducción del ancho de banda necesario','La consistencia entre los entornos de desarrollo y producción','La eliminación total de dependencias'], r:2, e:'Un contenedor empaqueta la aplicación y todas sus dependencias. El mismo contenedor funciona igual en local, staging y producción, eliminando el "en mi máquina funciona".' },
    { tema:'UF1', p:'¿Qué es un contenedor en el contexto del despliegue de aplicaciones?', ops:['Un dispositivo de almacenamiento físico','Un método de cifrado de datos','Un tipo de base de datos NoSQL','Un entorno de ejecución ligero y portátil para las aplicaciones'], r:3, e:'Un contenedor es una unidad estándar de software que empaqueta el código y todas sus dependencias, permitiendo ejecutar la aplicación de forma confiable en cualquier entorno.' },
    { tema:'UF1', p:'¿Qué modelo de servicio cloud ofrece almacenamiento y potencia de cálculo a través de Internet?', ops:['SaaS','PaaS','IaaS','FaaS'], r:2, e:'IaaS (Infrastructure as a Service) proporciona recursos de infraestructura virtualizados: servidores, almacenamiento y redes. Ejemplos: AWS EC2, Azure VMs.' },
    { tema:'UF1', p:'¿Qué es LDAP en términos de gestión de red?', ops:['Un protocolo de transferencia de archivos','Un protocolo de enrutamiento','Un protocolo de acceso a directorios','Un sistema de virtualización'], r:2, e:'LDAP (Lightweight Directory Access Protocol) es un protocolo estándar para acceder y gestionar servicios de directorio distribuidos, como Active Directory.' },
    { tema:'UF1', p:'¿Cuál es un ejemplo de SaaS en la computación en la nube?', ops:['Amazon EC2','Docker','Kubernetes','Microsoft Office 365'], r:3, e:'SaaS (Software as a Service): el proveedor gestiona todo y el usuario accede a la aplicación vía web. Office 365, Gmail, Salesforce son ejemplos típicos.' },
    { tema:'UF1', p:'¿Qué ventaja ofrece LDAP frente a los directorios tradicionales?', ops:['Mayor velocidad de transferencia de archivos','Mejor calidad de vídeo en streaming','Acceso y gestión eficientes de la información del directorio','Cifrado automático de todos los datos'], r:2, e:'LDAP permite acceder y gestionar información de directorios (usuarios, grupos, permisos) de forma eficiente y estandarizada sobre TCP/IP.' },
    { tema:'UF1', p:'¿Cuál es la característica clave del alojamiento compartido?', ops:['Control total sobre el hardware','Recursos dedicados exclusivos','Compartir un servidor con múltiples clientes','Escalado automático ilimitado'], r:2, e:'En el hosting compartido, múltiples clientes comparten los recursos del mismo servidor físico. Es el más económico pero con menor control y rendimiento.' },
    { tema:'UF1', p:'¿Para qué se utiliza principalmente el protocolo LDAP?', ops:['Para servir páginas web','Para enviar correos electrónicos','Para la autenticación y el acceso a la información de los directorios','Para la transferencia de archivos grandes'], r:2, e:'LDAP se usa principalmente para autenticación centralizada y para almacenar y consultar información de usuarios, grupos y recursos en una organización.' },
    { tema:'UF1', p:'¿Qué tipo de alojamiento web permite el máximo control sobre el servidor físico?', ops:['Alojamiento en la nube','Alojamiento compartido','Alojamiento VPS','Alojamiento dedicado'], r:3, e:'El servidor dedicado proporciona hardware exclusivo para un único cliente, con acceso root completo. Es el más caro pero el que ofrece máximo control y rendimiento.' },
    { tema:'UF1', p:'¿Qué modelo de servicio cloud proporciona plataformas para desarrollar, probar e implementar aplicaciones?', ops:['SaaS','IaaS','PaaS','FaaS'], r:2, e:'PaaS (Platform as a Service) proporciona el entorno completo de desarrollo y despliegue. El desarrollador solo gestiona el código. Ejemplos: Heroku, Google App Engine, Vercel.' },
    { tema:'UF1', p:'¿Qué representa un registro A en DNS?', ops:['La dirección de correo electrónico del dominio','El alias de un dominio','La dirección IP de un servidor','El servidor de nombres autoritativo'], r:2, e:'El registro A (Address) mapea un nombre de dominio a su dirección IPv4. Es el registro DNS más fundamental.' },
    { tema:'UF1', p:'¿Qué es el escalado horizontal en una aplicación web?', ops:['Aumentar la RAM y CPU de un servidor existente','Distribuir la carga entre múltiples servidores iguales','Aumentar el ancho de banda de la conexión','Comprimir los archivos estáticos'], r:1, e:'Escalado horizontal (scale out): añadir más servidores iguales. Mayor tolerancia a fallos que el escalado vertical. Requiere que la aplicación sea stateless.' },
    { tema:'UF1', p:'¿Qué es el escalado vertical en una aplicación web?', ops:['Añadir más servidores al sistema','Replicar la aplicación en múltiples regiones','Aumentar los recursos (RAM, CPU, disco) de un único servidor','Distribuir el tráfico con un balanceador de carga'], r:2, e:'Escalado vertical (scale up): aumentar los recursos del servidor existente. Tiene un límite físico máximo y crea punto único de fallo.' },
    { tema:'UF1', p:'¿Qué herramienta es el orquestador de contenedores más popular junto a Docker Compose?', ops:['Ansible','Terraform','Kubernetes','Puppet'], r:2, e:'Kubernetes (k8s) es el estándar de facto para orquestar contenedores a escala. Gestiona despliegue, escalado y recuperación automática de contenedores.' },
    { tema:'UF1', p:'¿Cuál es la diferencia entre un contenedor Docker y una máquina virtual?', ops:['No hay diferencia práctica','El contenedor incluye el SO completo; la VM no','El contenedor es más ligero porque comparte el kernel del SO anfitrión, sin necesitar un SO completo','Las VMs son más eficientes en rendimiento'], r:2, e:'Los contenedores comparten el kernel del SO anfitrión, lo que los hace mucho más ligeros y rápidos de iniciar que las VMs, que incluyen un SO completo cada una.' },
    { tema:'UF1', p:'¿Qué hace Docker Compose?', ops:['Compila imágenes Docker a partir de código fuente','Permite definir y ejecutar aplicaciones multi-contenedor con un fichero YAML','Es un registro de imágenes Docker','Es un sistema de orquestación equivalente a Kubernetes'], r:1, e:'Docker Compose usa un fichero docker-compose.yml para definir y gestionar múltiples contenedores que forman una aplicación (ej: app + base de datos + caché).' },
    { tema:'UF1', p:'¿Qué tipo de registro DNS se usa para aliasing (apuntar un dominio a otro nombre)?', ops:['Registro A','Registro MX','Registro CNAME','Registro NS'], r:2, e:'CNAME (Canonical Name) crea un alias de un dominio a otro. Ejemplo: www.ejemplo.com → ejemplo.com. MX apunta a servidores de correo, NS a servidores de nombres.' },
    { tema:'UF1', p:'¿Qué es el despliegue continuo (CD) en el contexto del desarrollo de software?', ops:['Actualizar el servidor manualmente cada semana','Un proceso automatizado que lleva cada cambio validado a producción','Un sistema de control de versiones','Una técnica de monitorización de servidores'], r:1, e:'CD (Continuous Deployment/Delivery): automatiza el despliegue a producción tras pasar los tests de CI. Reduce el tiempo entre escribir código y tenerlo en producción.' },
  ],

  // ─────────────────────────────────────────────────────────
  // UF2 — SERVIDORES WEB
  // HTTP/HTTPS · Apache · Hosting · Virtual hosts
  // ─────────────────────────────────────────────────────────
  UF2: [
    { tema:'UF2', p:'LAMP es el acrónimo de:', ops:['Linux, Android, MySQL, Pascal','LaTeX, Apache, MySQL, Pascal','Linux, Apache, MySQL, PHP','Linux, Android, MySQL, PHP'], r:2, e:'LAMP = Linux + Apache + MySQL + PHP. Es el stack libre más extendido para desarrollo web en entorno servidor.' },
    { tema:'UF2', p:'¿Cuál es el protocolo principal que se utiliza en la World Wide Web para acceder a la información?', ops:['HTML','TCP/IP','FTP','HTTP'], r:3, e:'HTTP (HyperText Transfer Protocol) es el protocolo de la capa de aplicación que permite la transferencia de recursos web entre cliente y servidor.' },
    { tema:'UF2', p:'¿Cuál es la función principal de un servidor web en la arquitectura cliente-servidor?', ops:['Hacer copias de seguridad de la información','Representar la información HTML','Consultar bases de datos','Estar siempre encendido a la espera de peticiones para buscar y servir información'], r:3, e:'El servidor web escucha peticiones HTTP, localiza el recurso solicitado y devuelve una respuesta. Siempre está en modo escucha.' },
    { tema:'UF2', p:'¿Qué versión de HTTP fue definida en la RFC 7540?', ops:['HTTP/1.0','HTTP/1.1','HTTP/2','HTTP/3'], r:2, e:'HTTP/2 fue definido en la RFC 7540 en 2015. Introduce multiplexación, compresión de cabeceras y Server Push, mejorando el rendimiento respecto a HTTP/1.1.' },
    { tema:'UF2', p:'HTTP es un protocolo sin estado. ¿Qué significa esto?', ops:['Que no puede transferir archivos binarios','Que cada petición es independiente y el servidor no recuerda peticiones anteriores','Que solo funciona con conexiones seguras','Que necesita autenticación en cada petición'], r:1, e:'HTTP es stateless: cada petición HTTP es completamente independiente. Para mantener estado (sesiones, login) se usan cookies, tokens o sesiones del lado servidor.' },
    { tema:'UF2', p:'¿Cuál es la función del método HTTP HEAD?', ops:['Transferir el recurso indicado del servidor al cliente','Borrar un recurso del servidor','Enviar información al servidor para su procesamiento','Obtener solo las cabeceras del recurso sin transferir el cuerpo'], r:3, e:'HEAD funciona como GET pero el servidor solo devuelve las cabeceras HTTP, sin el cuerpo. Útil para comprobar si un recurso existe o su fecha de modificación.' },
    { tema:'UF2', p:'¿Qué característica introdujo HTTP/1.1 respecto a las conexiones TCP?', ops:['Conexiones UDP en lugar de TCP','Cifrado obligatorio','Compresión de cabeceras','Conexiones persistentes que permiten varias peticiones HTTP por cada conexión TCP'], r:3, e:'HTTP/1.1 introdujo keep-alive por defecto: la conexión TCP se mantiene abierta para múltiples peticiones, evitando el overhead de abrir/cerrar TCP en cada una.' },
    { tema:'UF2', p:'En la arquitectura de tres niveles, ¿qué hace el servidor de aplicaciones?', ops:['Solo sirve archivos estáticos HTML','Consulta la base de datos para completar la información solicitada por el cliente','Gestiona directamente las peticiones del navegador y las sirve sin base de datos','Almacena los datos de la aplicación'], r:1, e:'En la arquitectura de tres niveles: cliente → servidor de aplicaciones → base de datos. El servidor de aplicaciones procesa la lógica y consulta la BD.' },
    { tema:'UF2', p:'¿Qué afirmación sobre TLS 1.3 es correcta?', ops:['Se publicó el año 2022 en la RFC 9110','Aún se trata de un borrador','Se publicó el año 2018 en la RFC 8446','Se publicó en 1997'], r:2, e:'TLS 1.3 fue publicado en agosto de 2018 en la RFC 8446. Elimina algoritmos obsoletos y reduce el handshake a 1-RTT, mejorando seguridad y velocidad.' },
    { tema:'UF2', p:'Un certificado digital contiene la clave privada de su propietario firmada con la clave pública de una CA. ¿Es esto correcto?', ops:['Verdadero, es la definición exacta','Falso: el certificado contiene la clave PÚBLICA del propietario, firmada con la clave PRIVADA de la CA','Verdadero, pero solo en certificados EV','Falso, los certificados no tienen ninguna clave'], r:1, e:'Un certificado X.509 contiene la clave PÚBLICA del propietario (nunca la privada) y está firmado digitalmente con la clave PRIVADA de la CA (Autoridad Certificadora).' },
    { tema:'UF2', p:'¿Qué es un host virtual basado en nombres en Apache?', ops:['Un servidor físico con varios nombres DNS','Múltiples sitios web en el mismo servidor, diferenciados por el nombre de dominio de la petición HTTP','Un proxy inverso para balanceo de carga','Una técnica para cifrar el tráfico HTTP'], r:1, e:'Los virtual hosts basados en nombres permiten alojar múltiples dominios (ejemplo.com, otroweb.es) en el mismo servidor con la misma IP, diferenciados por la cabecera Host.' },
    { tema:'UF2', p:'¿Qué código de estado HTTP indica que un recurso no se ha encontrado?', ops:['200','301','403','404'], r:3, e:'404 Not Found indica que el servidor no encontró el recurso solicitado. 200 es OK, 301 es redirección permanente, 403 es acceso prohibido.' },
    { tema:'UF2', p:'¿Qué diferencia hay entre HTTP/1.1 y HTTP/2 en el formato de los mensajes?', ops:['HTTP/2 usa XML en lugar de texto plano','HTTP/2 usa formato binario en lugar de texto ASCII','Son idénticos en formato, solo cambia la velocidad','HTTP/2 elimina las cabeceras HTTP'], r:1, e:'HTTP/2 usa un formato binario (no ASCII como HTTP/1.1), lo que permite mayor eficiencia en la multiplexación y menor tamaño de los mensajes.' },
    { tema:'UF2', p:'¿Qué significa que una empresa de hosting ofrezca un panel de control a sus clientes?', ops:['Que el cliente tiene acceso root al servidor','Que el cliente puede gestionar su sitio web (dominios, email, BD) de forma autónoma sin necesitar al soporte técnico para todo','Que el cliente puede modificar la configuración del servidor físico','Que el hosting es exclusivamente para desarrolladores'], r:1, e:'Los paneles de control (cPanel, Plesk, DirectAdmin) permiten a los clientes gestionar su alojamiento: crear subdominios, cuentas de email, bases de datos, etc.' },
    { tema:'UF2', p:'¿Qué es el protocolo HTTPS?', ops:['Una versión más rápida de HTTP sin cifrado','HTTP con cifrado TLS/SSL que garantiza confidencialidad e integridad de los datos transmitidos','Un protocolo alternativo a HTTP para transferir archivos','Una extensión de HTTP solo para APIs REST'], r:1, e:'HTTPS = HTTP + TLS. El protocolo TLS cifra la comunicación, garantizando que los datos no pueden ser leídos ni modificados por terceros en tránsito.' },
    { tema:'UF2', p:'¿Qué es la Infraestructura de Clave Pública (PKI)?', ops:['Un sistema de autenticación basado en contraseñas','Un conjunto de roles, políticas y procedimientos para gestionar certificados digitales y criptografía de clave pública','Un protocolo de transferencia segura de archivos','Un tipo de firewall para servidores web'], r:1, e:'PKI gestiona la emisión, revocación y validación de certificados digitales. Las CAs (Autoridades Certificadoras) son el elemento central de la PKI.' },
    { tema:'UF2', p:'¿Qué método HTTP se usa para enviar datos al servidor (por ejemplo, al enviar un formulario)?', ops:['GET','HEAD','DELETE','POST'], r:3, e:'POST envía datos en el cuerpo de la petición. GET los envía en la URL (query string). POST se usa para formularios, subida de archivos y creación de recursos en APIs REST.' },
    { tema:'UF2', p:'¿Qué versión de HTTP añadió multiplexación y Server Push?', ops:['HTTP/1.0','HTTP/1.1','HTTP/2','HTTP/3'], r:2, e:'HTTP/2 introdujo multiplexación (varias peticiones simultáneas en una conexión TCP), compresión de cabeceras (HPACK) y Server Push (enviar recursos proactivamente).' },
  ],

  // ─────────────────────────────────────────────────────────
  // UF3 — SERVIDORES DE APLICACIONES
  // Java EE · Apache Tomcat · Servlets · JSP · Sesiones
  // ─────────────────────────────────────────────────────────
  UF3: [
    { tema:'UF3', p:'¿Cuál es una desventaja del uso de servidores de aplicaciones?', ops:['Facilidad en la administración de actualizaciones','La menor necesidad de servidores potentes','La disminución de la administración de clientes','El incremento de la superficie de ataque, ya que se transmite información por la red'], r:3, e:'Al centralizar la aplicación, toda la comunicación pasa por la red, ampliando la superficie de ataque. También, si el servidor cae, todos los clientes quedan sin servicio.' },
    { tema:'UF3', p:'¿Para qué sirven las variables CATALINA_HOME y CATALINA_BASE en Tomcat?', ops:['Para almacenar los archivos temporales de la JVM','Para contener los elementos comunes a todas las instancias','Apuntan al directorio raíz de una única instalación','Permiten ejecutar varias instancias de Tomcat en una máquina apuntando al mismo directorio de instalación'], r:3, e:'CATALINA_HOME apunta al directorio de instalación de Tomcat. CATALINA_BASE permite que varias instancias compartan esa instalación con configuraciones independientes.' },
    { tema:'UF3', p:'¿Cuál de estas NO es una edición de la plataforma Java de Oracle?', ops:['Java Enterprise Edition (Java EE)','Java Micro Edition (Java ME)','Java Standard Edition (Java SE)','Java Microservice Edition (Java MSE)'], r:3, e:'Las ediciones oficiales son Java SE (escritorio/servidor básico), Java EE/Jakarta EE (empresarial) y Java ME (dispositivos embebidos). Java MSE no existe.' },
    { tema:'UF3', p:'¿Cuál es la diferencia principal entre cookies y sesiones en Java?', ops:['Las cookies almacenan datos en el servidor; las sesiones en el cliente','No hay diferencia, ambas almacenan en el servidor','Las sesiones almacenan información en el servidor; las cookies lo hacen en el cliente (navegador)','Las cookies son más seguras que las sesiones siempre'], r:2, e:'Cookies: datos en el cliente (navegador), enviadas en cada petición HTTP. Sesiones: datos en el servidor, identificadas por un ID de sesión en una cookie o URL.' },
    { tema:'UF3', p:'¿Qué medida de seguridad recomienda el temario para Tomcat?', ops:['Activar todas las aplicaciones de ejemplo incluidas en la instalación','No es necesario eliminar referencias a la versión de Tomcat','Deshabilitar el security manager siempre','Eliminar toda referencia a la versión de Tomcat para dificultar el uso de exploits'], r:3, e:'Ocultar la versión de Tomcat en cabeceras y páginas de error es una práctica básica de seguridad para dificultar que los atacantes identifiquen vulnerabilidades conocidas.' },
    { tema:'UF3', p:'¿Qué ventaja ofrecen los servidores de aplicaciones frente a un modelo descentralizado?', ops:['Una mayor superficie de ataque del sistema','La necesidad de servidores menos potentes','Una menor protección de la información en tránsito','La disminución de la administración de los clientes'], r:3, e:'Al centralizar la aplicación, los clientes no necesitan software instalado ni mantenimiento local. Solo necesitan un navegador. Reduce enormemente la administración cliente.' },
    { tema:'UF3', p:'¿Qué función tiene el archivo web.xml en una aplicación web en Tomcat?', ops:['Contiene las páginas HTML y JavaScript de la aplicación','Define las librerías externas necesarias','Se usa para almacenar archivos temporales','Describe los servlets y componentes de la aplicación, con parámetros de inicialización y restricciones de seguridad'], r:3, e:'web.xml es el descriptor de despliegue (Deployment Descriptor) de una aplicación Java EE. Define servlets, mappings de URL, filtros, parámetros de contexto y seguridad.' },
    { tema:'UF3', p:'¿Cómo se gestionan las cookies en Java/Servlets?', ops:['Con la clase SessionCookie del paquete javax.servlet.session','Con la interfaz HttpRequest y sus métodos addCookie y getCookie','Con la clase Cookie del paquete javax.servlet.http, con constructor nombre/valor y métodos como setValue','Con la clase ServletCookie del paquete jakarta.servlet'], r:2, e:'La clase javax.servlet.http.Cookie permite crear cookies con new Cookie(nombre, valor), configurarlas con setMaxAge(), setPath() y añadirlas con response.addCookie().' },
    { tema:'UF3', p:'¿Cuál es el nombre del contenedor de servlets de Apache Tomcat desde la versión 4.x?', ops:['Jasper','Tomcat Engine','JSP','Catalina'], r:3, e:'Catalina es el contenedor de servlets de Apache Tomcat (desde v4). Jasper es el motor JSP de Tomcat. Ambos son componentes del mismo servidor.' },
    { tema:'UF3', p:'¿Qué contiene la capa de datos en la arquitectura de plataformas Java?', ops:['La lógica de negocio de la aplicación','La interfaz de usuario (navegador o app)','Los servicios que proporcionan acceso a la información almacenada, normalmente en una base de datos','Los servlets que procesan las peticiones HTTP'], r:2, e:'La arquitectura Java EE tiene 4 capas: cliente, presentación, servicios de negocio y datos. La capa de datos gestiona la persistencia (JDBC, JPA, bases de datos).' },
    { tema:'UF3', p:'¿Cuál es la diferencia entre Apache Tomcat y Apache TomEE?', ops:['Tomcat y TomEE son exactamente iguales','Tomcat implementa todas las especificaciones Jakarta EE; TomEE solo algunas','Tomcat es una implementación de código abierto de algunas especificaciones Jakarta EE pero no es un servidor de aplicaciones completo; TomEE sí lo es','TomEE es más ligero que Tomcat'], r:2, e:'Tomcat es un contenedor de servlets/JSP (implementación parcial de Jakarta EE). TomEE añade soporte completo para CDI, EJB, JPA, etc., convirtiéndose en servidor de aplicaciones completo.' },
    { tema:'UF3', p:'¿Para qué sirven las sesiones en Java?', ops:['Para enviar información que el usuario ha pedido de una base de datos','Para almacenar pequeñas cantidades de información en el navegador','Para recibir información del usuario y almacenarla en base de datos','Para identificar y almacenar información sobre los usuarios cuando realizan varias peticiones al mismo servidor'], r:3, e:'Las sesiones permiten mantener estado entre peticiones HTTP (que es un protocolo sin estado). HttpSession almacena objetos en el servidor asociados a un usuario.' },
    { tema:'UF3', p:'¿Qué hace la capa de presentación en la arquitectura Java?', ops:['Ejecutar elementos en la máquina cliente','Proporcionar acceso a la información almacenada en una base de datos','Procesar las peticiones de la capa de servicios de negocios','Transformar la información a un formato legible para el cliente, generalmente HTML'], r:3, e:'La capa de presentación (JSP, Thymeleaf, servlets) genera la respuesta visual: convierte datos del modelo en HTML, JSON u otro formato que el cliente pueda consumir.' },
    { tema:'UF3', p:'¿Cuál es la naturaleza de Apache Tomcat?', ops:['Es un servidor de aplicaciones libre','Es un contenedor de servlets propietario','Es un servidor de aplicaciones propietario','Es un contenedor de servlets libre'], r:3, e:'Apache Tomcat es un contenedor de servlets y JSP de código abierto (Apache License). No es un servidor de aplicaciones completo, ya que no implementa todas las especificaciones Jakarta EE.' },
    { tema:'UF3', p:'Tras modificar un archivo .java y compilarlo a .class, ¿qué acción se usa en el gestor de Tomcat para aplicar los cambios sin reiniciar?', ops:['Arrancar','Parar','Replegar','Recargar'], r:3, e:'Recargar (Reload) en el gestor de aplicaciones de Tomcat recarga la aplicación web, liberando caché y aplicando los nuevos archivos .class sin reiniciar todo Tomcat.' },
    { tema:'UF3', p:'¿Qué es Java bytecode?', ops:['El código máquina generado directamente para Windows','Un código intermedio generado por el compilador Java que la JVM interpreta','El código fuente Java antes de compilar','Un tipo especial de código C++ compatible con Java'], r:1, e:'Java compila a bytecode (archivos .class), un código intermedio independiente de la plataforma. La JVM de cada sistema operativo interpreta ese bytecode, permitiendo "compilar una vez, ejecutar en cualquier parte".' },
    { tema:'UF3', p:'¿Qué es la JVM?', ops:['El compilador de Java','El IDE oficial de Oracle para Java','La máquina virtual de Java que interpreta el bytecode y lo ejecuta en cualquier plataforma','Un servidor de aplicaciones Java'], r:2, e:'JVM (Java Virtual Machine) interpreta el bytecode Java y lo ejecuta en el hardware específico. Cada SO tiene su JVM, pero el mismo bytecode funciona en todas.' },
  ],

  // ─────────────────────────────────────────────────────────
  // UF4 — TRANSFERENCIA DE ARCHIVOS
  // FTP · FTPS · SFTP · SSH · FileZilla
  // ─────────────────────────────────────────────────────────
  UF4: [
    { tema:'UF4', p:'¿Cuántos canales de conexión usa el protocolo FTP?', ops:['Uno: canal de datos','Dos: canal de control (comandos) y canal de datos','Tres: control, datos y seguridad','Uno: canal de control únicamente'], r:1, e:'FTP usa dos conexiones TCP separadas: el canal de control (puerto 21) para comandos y respuestas, y el canal de datos (puerto 20 en modo activo) para la transferencia.' },
    { tema:'UF4', p:'¿Cuál es la diferencia entre el modo activo y el modo pasivo en FTP?', ops:['En modo activo, el servidor conecta al cliente para el canal de datos; en modo pasivo, el cliente conecta al servidor','Son idénticos, es solo una nomenclatura diferente','En modo pasivo, el servidor inicia siempre ambas conexiones','En modo activo, el cliente inicia ambas conexiones'], r:0, e:'Modo activo: el servidor abre conexión de datos hacia el cliente (problemático con NAT/firewall). Modo pasivo: el cliente inicia también la conexión de datos, más compatible con firewalls.' },
    { tema:'UF4', p:'¿Qué protocolo de transferencia de archivos cifra la comunicación usando SSH?', ops:['FTP','FTPS','SFTP','SCP únicamente'], r:2, e:'SFTP (SSH File Transfer Protocol) transfiere archivos sobre una conexión SSH cifrada. A pesar del nombre, no es una extensión de FTP sino un protocolo independiente.' },
    { tema:'UF4', p:'¿Qué hace el protocolo FTPS?', ops:['Es igual que SFTP pero más antiguo','Es FTP con cifrado TLS/SSL añadido','Es un protocolo basado en SSH para transferencia segura','Es una versión de FTP que solo funciona en redes locales'], r:1, e:'FTPS (FTP over TLS/SSL) añade cifrado TLS al protocolo FTP estándar. Definido en la RFC 4217. Distinto de SFTP, que es un protocolo diferente basado en SSH.' },
    { tema:'UF4', p:'¿Qué cliente de FTP multiplataforma es ampliamente usado e incluye interfaz gráfica?', ops:['WinSCP','Cyberduck','FileZilla','PuTTY'], r:2, e:'FileZilla es uno de los clientes FTP/FTPS/SFTP más populares. Tiene versión de escritorio (gráfica) y también versión servidor. Es multiplataforma y gratuito.' },
    { tema:'UF4', p:'¿Qué permite el acceso anónimo en FTP?', ops:['Acceso sin usuario ni contraseña para descargar archivos públicos','Acceso con el usuario "root" sin contraseña','Acceso cifrado sin autenticación','Acceso con cualquier contraseña válida del sistema'], r:0, e:'El acceso anónimo FTP permite que usuarios sin cuenta descarguen archivos públicos usando "anonymous" como usuario y cualquier email como contraseña. Útil para distribución pública.' },
    { tema:'UF4', p:'¿Qué es SSHFS?', ops:['Un tipo de servidor FTP basado en SSH','Un sistema de archivos que permite montar directorios remotos de forma local a través de SSH','Un protocolo de cifrado para FTPS','Una herramienta de auditoría SSH'], r:1, e:'SSHFS (SSH FileSystem) permite montar un directorio remoto como si fuera local, usando SFTP/SSH como transporte. El usuario puede trabajar con archivos remotos con sus aplicaciones locales.' },
    { tema:'UF4', p:'¿Qué protocolo usa el puerto 21 por defecto?', ops:['SFTP','SSH','FTPS','FTP (canal de control)'], r:3, e:'FTP usa el puerto 21 para el canal de control (comandos). El canal de datos usa el puerto 20 en modo activo. SSH/SFTP usan el puerto 22.' },
    { tema:'UF4', p:'¿Cuál es la principal diferencia de seguridad entre FTP y SFTP?', ops:['FTP es más seguro porque usa dos canales','SFTP cifra tanto los datos como las credenciales; FTP transmite todo en texto plano','FTP usa TLS; SFTP usa algoritmos propietarios','No hay diferencia de seguridad entre ambos'], r:1, e:'FTP transmite usuario, contraseña y datos en texto plano (interceptable con sniffers). SFTP cifra toda la comunicación dentro del túnel SSH.' },
    { tema:'UF4', p:'¿Qué servidor FTP libre se menciona en el temario para instalación en Linux?', ops:['ProFTPD','vsftpd','PureFTPD','FileZilla Server'], r:1, e:'vsftpd (Very Secure FTP Daemon) es el servidor FTP recomendado en el temario. Es ligero, seguro y ampliamente usado en sistemas Linux.' },
    { tema:'UF4', p:'¿Qué es OpenSSH?', ops:['Un protocolo de transferencia de archivos propietario','Una implementación libre del protocolo SSH que incluye cliente y servidor SSH, además de soporte SFTP','Un servidor web alternativo a Apache','Un sistema de gestión de certificados SSL'], r:1, e:'OpenSSH es la implementación libre más popular de SSH. Incluye el servidor sshd, el cliente ssh, scp y sftp. Viene instalado por defecto en la mayoría de distribuciones Linux.' },
    { tema:'UF4', p:'¿Qué tipo de datos puede transferir FTP?', ops:['Solo archivos de texto ASCII','Solo archivos binarios','Archivos en modo ASCII (texto) o binario, según configuración','Solo archivos menores de 4GB'], r:2, e:'FTP admite dos modos de transferencia: ASCII (para archivos de texto, convierte saltos de línea) y binario (para cualquier tipo de archivo sin conversión). Hay que elegir el modo correcto.' },
    { tema:'UF4', p:'¿Cuál es el protocolo indicado para entornos donde hay NAT o firewalls que bloquean conexiones entrantes?', ops:['FTP en modo activo','FTP en modo pasivo','Telnet','TFTP'], r:1, e:'El modo pasivo FTP es el recomendado cuando el cliente está detrás de NAT o firewall, ya que el cliente es quien inicia ambas conexiones (no hay conexión entrante al cliente).' },
  ],

  // ─────────────────────────────────────────────────────────
  // UF5 — DOCUMENTACIÓN Y CONTROL DE VERSIONES
  // Git · GitHub · Javadoc · MediaWiki · Man · CI/CD
  // ─────────────────────────────────────────────────────────
  UF5: [
    { tema:'UF5', p:'¿Por qué es tan habitual encontrar software sin documentar?', ops:['Porque las herramientas de documentación son muy caras','Porque los usuarios ya conocen el software y no necesitan manuales','Porque requiere personal externo y es muy costoso','Porque falta tiempo, no se le da la importancia que merece y documentar tiene fama de ser un trabajo aburrido'], r:3, e:'Las razones más comunes son: plazos ajustados, cultura empresarial que no valora la documentación y percepción entre los desarrolladores de que es un trabajo tedioso.' },
    { tema:'UF5', p:'¿Cuáles son las fases del ciclo de vida del software según el temario?', ops:['Análisis, diseño, programación, pruebas, despliegue y mantenimiento','Recogida de requisitos, diseño, implementación, prueba, despliegue y mantenimiento','Recogida y análisis de requerimientos, especificación, implementación, comprobación, despliegue y mantenimiento','Planificación, desarrollo, QA y producción'], r:2, e:'El ciclo de vida incluye: recogida y análisis de requerimientos → especificación → implementación/desarrollo → comprobación → despliegue → mantenimiento.' },
    { tema:'UF5', p:'¿Cuál es una característica importante de los comentarios Javadoc en Java?', ops:['Deben comenzar con "//" y tener máximo 100 caracteres','Deben comenzar con "/*" y terminar con "*/"','Deben contener un primer bloque de descripción seguido de etiquetas precedidas por "@"','Solo documentan clases, no métodos ni parámetros'], r:2, e:'Los comentarios Javadoc (/** ... */) contienen: descripción del elemento y etiquetas @param, @return, @throws, @author, @version, etc. La herramienta javadoc genera HTML a partir de ellos.' },
    { tema:'UF5', p:'¿Para qué sirve el control de versiones?', ops:['Solo para indicar al usuario la versión instalada','Solo en la fase de diseño para contar propuestas','Para tener un registro de los cambios realizados a lo largo de la vida útil de un programa','Solo en la fase de pruebas para anotar los fallos'], r:2, e:'El control de versiones registra todos los cambios: quién hizo qué, cuándo y por qué. Permite volver a versiones anteriores, trabajar en paralelo y colaborar en equipo.' },
    { tema:'UF5', p:'¿Qué áreas de trabajo utiliza Git?', ops:['Solo el repositorio','Solo el directorio de trabajo y el repositorio','Solo el área de preparación y el repositorio','El directorio de trabajo, el área de preparación (staging) y el repositorio'], r:3, e:'Git tiene tres áreas: directorio de trabajo (archivos editados), staging/índice (cambios preparados con git add) y repositorio (historial de commits con git commit).' },
    { tema:'UF5', p:'¿Con qué comando de Git se eliminan archivos del directorio de trabajo y del área de preparación?', ops:['action_delete','action_remove','reset','git rm'], r:3, e:'git rm elimina el archivo del directorio de trabajo y lo marca para eliminación en el próximo commit. git rm --cached lo elimina solo del staging, manteniendo el archivo local.' },
    { tema:'UF5', p:'¿Cuál es la utilidad principal de la herramienta Man en sistemas Unix?', ops:['Facilitar el desarrollo colaborativo de documentación','Proporcionar una interfaz gráfica para los manuales','Permitir la edición colaborativa de wikis','Ofrecer una interfaz de línea de comandos para acceder a los manuales de referencia del sistema'], r:3, e:'Man (manual) es el sistema de ayuda de Unix/Linux. Desde la terminal: "man comando" muestra la página de manual con descripción, opciones y ejemplos de uso.' },
    { tema:'UF5', p:'¿Qué ventaja ofrece MediaWiki como plataforma de documentación?', ops:['Permite generar documentación en HTML a partir de Java','Proporciona interfaz gráfica para manuales del sistema','Facilita la creación colaborativa y centralizada de documentación multilenguaje, actualizable y fiable','Solo sirve para documentar código fuente'], r:2, e:'MediaWiki (el software detrás de Wikipedia) permite que múltiples usuarios colaboren en la documentación, con historial de cambios, búsqueda y organización en categorías.' },
    { tema:'UF5', p:'¿Cuál es el propósito principal de la integración continua (CI) en GitHub?', ops:['Publicar nuevas versiones del producto inmediatamente después de su desarrollo','Detectar conflictos y realizar pruebas manualmente en cada cambio','Realizar pruebas e integrar automáticamente los cambios de programación en un repositorio compartido','Gestionar el acceso de los colaboradores al repositorio'], r:2, e:'CI automatiza: al hacer push, se ejecutan automáticamente los tests, análisis de código y build. Si algo falla, se notifica inmediatamente antes de que llegue a producción.' },
    { tema:'UF5', p:'¿Qué sección de los manuales de Man está reservada para los programas ejecutables y órdenes del shell?', ops:['Sección 2','Sección 5','Sección 4','Sección 1'], r:3, e:'La sección 1 de Man contiene comandos de usuario y shell. Sección 2: llamadas al sistema. Sección 3: funciones de biblioteca. Sección 5: formatos de archivo. Sección 8: comandos de administración.' },
    { tema:'UF5', p:'¿Cuál es una ventaja de trabajar con ramas (branches) en Git?', ops:['Facilita la creación de repositorios distribuidos','Permite eliminar los conflictos entre programadores','Permite eliminar el historial de cambios antiguo','Permite trabajar en paralelo en diferentes funcionalidades sin afectar a la rama principal'], r:3, e:'Las ramas permiten desarrollar features, corregir bugs o experimentar de forma aislada. Solo se fusionan (merge) a main/master cuando están probadas y aprobadas.' },
    { tema:'UF5', p:'¿Qué debe contener siempre el repositorio en un sistema de control de versiones?', ops:['Solo los archivos de código fuente, sin historial','Una copia por cada desarrollador del equipo','La última versión válida del programa','Solo los archivos modificados en el último sprint'], r:2, e:'El repositorio central debe contener siempre la última versión estable y funcional. Los desarrolladores trabajan en ramas y solo integran cuando el código pasa las pruebas.' },
    { tema:'UF5', p:'¿Por qué es importante estructurar adecuadamente la documentación del software?', ops:['Para evitar errores en el código y mejorar la seguridad','Para hacerla más atractiva visualmente','Para que sea entendible y útil para el público objetivo, localizar información rápido y conseguir documentación homogénea','Para reducir el tiempo de redacción'], r:2, e:'Una buena estructura documental: índice claro, secciones bien organizadas, ejemplos contextualizados y formato estándar, permiten a cualquier persona encontrar y entender la información.' },
    { tema:'UF5', p:'¿Cómo se indica en wikitexto (MediaWiki) que un texto debe aparecer en negrita?', ops:["== Texto ==","=== Texto ===","''Texto''","'''Texto'''"], r:3, e:"En wikitexto: '''texto''' = negrita, ''texto'' = cursiva, == Texto == = título de sección nivel 2, === Texto === = subsección nivel 3." },
    { tema:'UF5', p:'¿Qué comando Git se usa para crear un nuevo commit con los cambios del área de preparación?', ops:['git push','git add','git commit -m "mensaje"','git merge'], r:2, e:'git commit -m "mensaje" crea un snapshot permanente de los cambios en staging. git add mueve cambios al staging. git push sube commits al repositorio remoto.' },
    { tema:'UF5', p:'¿Qué es un repositorio remoto en Git?', ops:['Una copia local del proyecto en otro disco duro','Una versión cifrada del repositorio local','Un repositorio alojado en un servidor (GitHub, GitLab, Bitbucket) que sirve de punto central de colaboración','Una rama especial del repositorio'], r:2, e:'El repositorio remoto (origin) está en un servidor accesible por el equipo. git push sube cambios, git pull los descarga. GitHub/GitLab alojan repositorios remotos.' },
    { tema:'UF5', p:'¿Qué hace git clone?', ops:['Crea una nueva rama en el repositorio','Descarga una copia completa de un repositorio remoto, incluyendo todo el historial','Solo descarga los últimos cambios del repositorio remoto','Fusiona dos ramas del repositorio'], r:1, e:'git clone crea una copia local completa del repositorio remoto: todos los archivos, todas las ramas y todo el historial de commits. Es el punto de partida para colaborar.' },
    { tema:'UF5', p:'¿Qué es un Pull Request (PR) en GitHub?', ops:['Una solicitud para descargar cambios del repositorio remoto','Un mecanismo para proponer la fusión de cambios de una rama en otra, con revisión de código','Una forma de reportar bugs en el código','Una operación para revertir commits anteriores'], r:1, e:'Un PR propone fusionar cambios de una rama (feature branch) en otra (main). Permite revisión de código, comentarios y aprobación por parte del equipo antes de hacer el merge.' },
  ],

};
