// ═══════════════════════════════════════════════════════════════════
// BANCO DE PREGUNTAS — Despliegue de Aplicaciones Web (0614)
// Basado en temario UAX + cuestionarios oficiales UF1–UF5
// ═══════════════════════════════════════════════════════════════════

const BANCO = {

  // ─────────────────────────────────────────────────────────
  // UF1 — SERVICIOS DE RED IMPLICADOS EN EL DESPLIEGUE
  // DNS · LDAP · Cloud · Contenedores
  // ─────────────────────────────────────────────────────────
  UF1: [
    { tema:'UF1', p:'¿Qué tecnología es fundamental para el despliegue de contenedores?', ops:['Los balanceadores de carga','La virtualización','Los firewalls','Los proxies inversos'], r:1, e:'La virtualización es la tecnología base que hace posible los contenedores: permite ejecutar entornos aislados sobre el mismo hardware físico.' },
    { tema:'UF1', p:'En DNS, ¿qué es un dominio de nivel superior (TLD)?', ops:['El primer servidor DNS en la jerarquía','Un registro que apunta a un servidor de correo','El último segmento de un nombre de dominio','El servidor autoritativo de una zona'], r:2, e:'TLD = Top Level Domain. Es el último segmento del nombre de dominio: .com, .es, .org, etc. Están gestionados por la ICANN.' },
    { tema:'UF1', p:'¿Qué tipo de alojamiento web utiliza recursos de múltiples servidores para equilibrar la carga y maximizar la disponibilidad?', ops:['Alojamiento dedicado','Alojamiento VPS','Alojamiento en la nube','Alojamiento compartido'], r:2, e:'El cloud hosting distribuye la carga entre múltiples servidores. Si uno falla, otros asumen la carga. Ofrece alta disponibilidad y escalabilidad elástica.' },
    { tema:'UF1', p:'¿Cómo afecta el alojamiento en la nube a la escalabilidad de una aplicación web?', ops:['Reduce la capacidad de escalar','No tiene impacto en la escalabilidad','Requiere intervención manual para cada cambio','Facilita el escalado rápido y eficiente de recursos'], r:3, e:'El cloud permite escalar vertical u horizontalmente de forma casi inmediata, sin necesidad de adquirir hardware físico nuevo.' },
    { tema:'UF1', p:'¿Cuál es la ventaja principal del despliegue de contenedores?', ops:['El aumento de la seguridad cibernética','La reducción del ancho de banda necesario','La consistencia entre los entornos de desarrollo y producción','La eliminación total de dependencias'], r:2, e:'Un contenedor empaqueta la aplicación y todas sus dependencias. El mismo contenedor funciona igual en local, staging y producción, eliminando el "en mi máquina funciona".' },
    { tema:'UF1', p:'¿Qué es un contenedor en el contexto del despliegue de aplicaciones?', ops:['Un dispositivo de almacenamiento físico','Un método de cifrado de datos','Un tipo de base de datos NoSQL','Un entorno de ejecución ligero y portátil para las aplicaciones'], r:3, e:'Un contenedor es una unidad estándar de software que empaqueta el código y todas sus dependencias, permitiendo ejecutar la aplicación de forma confiable en cualquier entorno.' },
    { tema:'UF1', p:'¿Qué modelo de servicio cloud ofrece almacenamiento y potencia de cálculo a través de Internet?', ops:['SaaS','PaaS','IaaS','FaaS'], r:2, e:'IaaS (Infrastructure as a Service) proporciona recursos de infraestructura virtualizados: servidores, almacenamiento y redes. Ejemplos: AWS EC2, Azure VMs.' },
    { tema:'UF1', p:'¿Qué es LDAP en términos de gestión de red?', ops:['Un protocolo de transferencia de archivos','Un protocolo de enrutamiento','Un protocolo de acceso a directorios','Un sistema de virtualización'], r:2, e:'LDAP (Lightweight Directory Access Protocol) es un protocolo estándar para acceder y gestionar servicios de directorio distribuidos, como Active Directory.' },
    { tema:'UF1', p:'¿Cuál es un ejemplo de SaaS en la computación en la nube?', ops:['Amazon EC2','Docker','Kubernetes','Microsoft Office 365'], r:3, e:'SaaS (Software as a Service): el proveedor gestiona todo y el usuario accede a la aplicación vía web. Office 365, Gmail, Salesforce son ejemplos típicos.' },
    { tema:'UF1', p:'¿Qué ventaja ofrece LDAP frente a los directorios tradicionales?', ops:['Mayor velocidad de transferencia de archivos','Mejor calidad de vídeo en streaming','Acceso y gestión eficientes de la información del directorio','Cifrado automático de todos los datos'], r:2, e:'LDAP permite acceder y gestionar información de directorios (usuarios, grupos, permisos) de forma eficiente y estandarizada sobre TCP/IP.' },
    { tema:'UF1', p:'¿Cuál es la característica clave del alojamiento compartido?', ops:['Control total sobre el hardware','Recursos dedicados exclusivos','Compartir un servidor con múltiples clientes','Escalado automático ilimitado'], r:2, e:'En el hosting compartido, múltiples clientes comparten los recursos del mismo servidor físico. Es el más económico pero con menor control y rendimiento.' },
    { tema:'UF1', p:'¿Para qué se utiliza principalmente el protocolo LDAP?', ops:['Para servir páginas web','Para enviar correos electrónicos','Para la autenticación y el acceso a la información de los directorios','Para la transferencia de archivos grandes'], r:2, e:'LDAP se usa principalmente para autenticación centralizada y para almacenar y consultar información de usuarios, grupos y recursos en una organización.' },
    { tema:'UF1', p:'¿Qué tipo de alojamiento web permite el máximo control sobre el servidor físico?', ops:['Alojamiento en la nube','Alojamiento compartido','Alojamiento VPS','Alojamiento dedicado'], r:3, e:'El servidor dedicado proporciona hardware exclusivo para un único cliente, con acceso root completo. Es el más caro pero el que ofrece máximo control y rendimiento.' },
    { tema:'UF1', p:'¿Qué modelo de servicio cloud proporciona plataformas para desarrollar, probar e implementar aplicaciones?', ops:['SaaS','IaaS','PaaS','FaaS'], r:2, e:'PaaS (Platform as a Service) proporciona el entorno completo de desarrollo y despliegue. El desarrollador solo gestiona el código. Ejemplos: Heroku, Google App Engine, Vercel.' },
    { tema:'UF1', p:'¿Qué representa un registro A en DNS?', ops:['La dirección de correo electrónico del dominio','El alias de un dominio','La dirección IP de un servidor','El servidor de nombres autoritativo'], r:2, e:'El registro A (Address) mapea un nombre de dominio a su dirección IPv4. Es el registro DNS más fundamental.' },
    { tema:'UF1', p:'¿Qué es el escalado horizontal en una aplicación web?', ops:['Aumentar la RAM y CPU de un servidor existente','Distribuir la carga entre múltiples servidores iguales','Aumentar el ancho de banda de la conexión','Comprimir los archivos estáticos'], r:1, e:'Escalado horizontal (scale out): añadir más servidores iguales. Mayor tolerancia a fallos que el escalado vertical. Requiere que la aplicación sea stateless.' },
    { tema:'UF1', p:'¿Qué es el escalado vertical en una aplicación web?', ops:['Añadir más servidores al sistema','Replicar la aplicación en múltiples regiones','Aumentar los recursos (RAM, CPU, disco) de un único servidor','Distribuir el tráfico con un balanceador de carga'], r:2, e:'Escalado vertical (scale up): aumentar los recursos del servidor existente. Tiene un límite físico máximo y crea punto único de fallo.' },
    { tema:'UF1', p:'¿Qué herramienta es el orquestador de contenedores más popular junto a Docker Compose?', ops:['Ansible','Terraform','Kubernetes','Puppet'], r:2, e:'Kubernetes (k8s) es el estándar de facto para orquestar contenedores a escala. Gestiona despliegue, escalado y recuperación automática de contenedores.' },
    { tema:'UF1', p:'¿Cuál es la diferencia entre un contenedor Docker y una máquina virtual?', ops:['No hay diferencia práctica','El contenedor incluye el SO completo; la VM no','El contenedor es más ligero porque comparte el kernel del SO anfitrión, sin necesitar un SO completo','Las VMs son más eficientes en rendimiento'], r:2, e:'Los contenedores comparten el kernel del SO anfitrión, lo que los hace mucho más ligeros y rápidos de iniciar que las VMs, que incluyen un SO completo cada una.' },
    { tema:'UF1', p:'¿Qué hace Docker Compose?', ops:['Compila imágenes Docker a partir de código fuente','Permite definir y ejecutar aplicaciones multi-contenedor con un fichero YAML','Es un registro de imágenes Docker','Es un sistema de orquestación equivalente a Kubernetes'], r:1, e:'Docker Compose usa un fichero docker-compose.yml para definir y gestionar múltiples contenedores que forman una aplicación (ej: app + base de datos + caché).' },
    { tema:'UF1', p:'¿Qué tipo de registro DNS se usa para aliasing (apuntar un dominio a otro nombre)?', ops:['Registro A','Registro MX','Registro CNAME','Registro NS'], r:2, e:'CNAME (Canonical Name) crea un alias de un dominio a otro. Ejemplo: www.ejemplo.com → ejemplo.com. MX apunta a servidores de correo, NS a servidores de nombres.' },
    { tema:'UF1', p:'¿Qué es el despliegue continuo (CD) en el contexto del desarrollo de software?', ops:['Actualizar el servidor manualmente cada semana','Un proceso automatizado que lleva cada cambio validado a producción','Un sistema de control de versiones','Una técnica de monitorización de servidores'], r:1, e:'CD (Continuous Deployment/Delivery): automatiza el despliegue a producción tras pasar los tests de CI. Reduce el tiempo entre escribir código y tenerlo en producción.' },
  ],

  // ─────────────────────────────────────────────────────────
  // UF2 — SERVIDORES WEB
  // HTTP/HTTPS · Apache · Hosting · Virtual hosts
  // ─────────────────────────────────────────────────────────
  UF2: [
    { tema:'UF2', p:'LAMP es el acrónimo de:', ops:['Linux, Android, MySQL, Pascal','LaTeX, Apache, MySQL, Pascal','Linux, Apache, MySQL, PHP','Linux, Android, MySQL, PHP'], r:2, e:'LAMP = Linux + Apache + MySQL + PHP. Es el stack libre más extendido para desarrollo web en entorno servidor.' },
    { tema:'UF2', p:'¿Cuál es el protocolo principal que se utiliza en la World Wide Web para acceder a la información?', ops:['HTML','TCP/IP','FTP','HTTP'], r:3, e:'HTTP (HyperText Transfer Protocol) es el protocolo de la capa de aplicación que permite la transferencia de recursos web entre cliente y servidor.' },
    { tema:'UF2', p:'¿Cuál es la función principal de un servidor web en la arquitectura cliente-servidor?', ops:['Hacer copias de seguridad de la información','Representar la información HTML','Consultar bases de datos','Estar siempre encendido a la espera de peticiones para buscar y servir información'], r:3, e:'El servidor web escucha peticiones HTTP, localiza el recurso solicitado y devuelve una respuesta. Siempre está en modo escucha.' },
    { tema:'UF2', p:'¿Qué versión de HTTP fue definida en la RFC 7540?', ops:['HTTP/1.0','HTTP/1.1','HTTP/2','HTTP/3'], r:2, e:'HTTP/2 fue definido en la RFC 7540 en 2015. Introduce multiplexación, compresión de cabeceras y Server Push, mejorando el rendimiento respecto a HTTP/1.1.' },
    { tema:'UF2', p:'HTTP es un protocolo sin estado. ¿Qué significa esto?', ops:['Que no puede transferir archivos binarios','Que cada petición es independiente y el servidor no recuerda peticiones anteriores','Que solo funciona con conexiones seguras','Que necesita autenticación en cada petición'], r:1, e:'HTTP es stateless: cada petición HTTP es completamente independiente. Para mantener estado (sesiones, login) se usan cookies, tokens o sesiones del lado servidor.' },
    { tema:'UF2', p:'¿Cuál es la función del método HTTP HEAD?', ops:['Transferir el recurso indicado del servidor al cliente','Borrar un recurso del servidor','Enviar información al servidor para su procesamiento','Obtener solo las cabeceras del recurso sin transferir el cuerpo'], r:3, e:'HEAD funciona como GET pero el servidor solo devuelve las cabeceras HTTP, sin el cuerpo. Útil para comprobar si un recurso existe o su fecha de modificación.' },
    { tema:'UF2', p:'¿Qué característica introdujo HTTP/1.1 respecto a las conexiones TCP?', ops:['Conexiones UDP en lugar de TCP','Cifrado obligatorio','Compresión de cabeceras','Conexiones persistentes que permiten varias peticiones HTTP por cada conexión TCP'], r:3, e:'HTTP/1.1 introdujo keep-alive por defecto: la conexión TCP se mantiene abierta para múltiples peticiones, evitando el overhead de abrir/cerrar TCP en cada una.' },
    { tema:'UF2', p:'En la arquitectura de tres niveles, ¿qué hace el servidor de aplicaciones?', ops:['Solo sirve archivos estáticos HTML','Consulta la base de datos para completar la información solicitada por el cliente','Gestiona directamente las peticiones del navegador y las sirve sin base de datos','Almacena los datos de la aplicación'], r:1, e:'En la arquitectura de tres niveles: cliente → servidor de aplicaciones → base de datos. El servidor de aplicaciones procesa la lógica y consulta la BD.' },
    { tema:'UF2', p:'¿Qué afirmación sobre TLS 1.3 es correcta?', ops:['Se publicó el año 2022 en la RFC 9110','Aún se trata de un borrador','Se publicó el año 2018 en la RFC 8446','Se publicó en 1997'], r:2, e:'TLS 1.3 fue publicado en agosto de 2018 en la RFC 8446. Elimina algoritmos obsoletos y reduce el handshake a 1-RTT, mejorando seguridad y velocidad.' },
    { tema:'UF2', p:'Un certificado digital contiene la clave privada de su propietario firmada con la clave pública de una CA. ¿Es esto correcto?', ops:['Verdadero, es la definición exacta','Falso: el certificado contiene la clave PÚBLICA del propietario, firmada con la clave PRIVADA de la CA','Verdadero, pero solo en certificados EV','Falso, los certificados no tienen ninguna clave'], r:1, e:'Un certificado X.509 contiene la clave PÚBLICA del propietario (nunca la privada) y está firmado digitalmente con la clave PRIVADA de la CA (Autoridad Certificadora).' },
    { tema:'UF2', p:'¿Qué es un host virtual basado en nombres en Apache?', ops:['Un servidor físico con varios nombres DNS','Múltiples sitios web en el mismo servidor, diferenciados por el nombre de dominio de la petición HTTP','Un proxy inverso para balanceo de carga','Una técnica para cifrar el tráfico HTTP'], r:1, e:'Los virtual hosts basados en nombres permiten alojar múltiples dominios (ejemplo.com, otroweb.es) en el mismo servidor con la misma IP, diferenciados por la cabecera Host.' },
    { tema:'UF2', p:'¿Qué código de estado HTTP indica que un recurso no se ha encontrado?', ops:['200','301','403','404'], r:3, e:'404 Not Found indica que el servidor no encontró el recurso solicitado. 200 es OK, 301 es redirección permanente, 403 es acceso prohibido.' },
    { tema:'UF2', p:'¿Qué diferencia hay entre HTTP/1.1 y HTTP/2 en el formato de los mensajes?', ops:['HTTP/2 usa XML en lugar de texto plano','HTTP/2 usa formato binario en lugar de texto ASCII','Son idénticos en formato, solo cambia la velocidad','HTTP/2 elimina las cabeceras HTTP'], r:1, e:'HTTP/2 usa un formato binario (no ASCII como HTTP/1.1), lo que permite mayor eficiencia en la multiplexación y menor tamaño de los mensajes.' },
    { tema:'UF2', p:'¿Qué significa que una empresa de hosting ofrezca un panel de control a sus clientes?', ops:['Que el cliente tiene acceso root al servidor','Que el cliente puede gestionar su sitio web (dominios, email, BD) de forma autónoma sin necesitar al soporte técnico para todo','Que el cliente puede modificar la configuración del servidor físico','Que el hosting es exclusivamente para desarrolladores'], r:1, e:'Los paneles de control (cPanel, Plesk, DirectAdmin) permiten a los clientes gestionar su alojamiento: crear subdominios, cuentas de email, bases de datos, etc.' },
    { tema:'UF2', p:'¿Qué es el protocolo HTTPS?', ops:['Una versión más rápida de HTTP sin cifrado','HTTP con cifrado TLS/SSL que garantiza confidencialidad e integridad de los datos transmitidos','Un protocolo alternativo a HTTP para transferir archivos','Una extensión de HTTP solo para APIs REST'], r:1, e:'HTTPS = HTTP + TLS. El protocolo TLS cifra la comunicación, garantizando que los datos no pueden ser leídos ni modificados por terceros en tránsito.' },
    { tema:'UF2', p:'¿Qué es la Infraestructura de Clave Pública (PKI)?', ops:['Un sistema de autenticación basado en contraseñas','Un conjunto de roles, políticas y procedimientos para gestionar certificados digitales y criptografía de clave pública','Un protocolo de transferencia segura de archivos','Un tipo de firewall para servidores web'], r:1, e:'PKI gestiona la emisión, revocación y validación de certificados digitales. Las CAs (Autoridades Certificadoras) son el elemento central de la PKI.' },
    { tema:'UF2', p:'¿Qué método HTTP se usa para enviar datos al servidor (por ejemplo, al enviar un formulario)?', ops:['GET','HEAD','DELETE','POST'], r:3, e:'POST envía datos en el cuerpo de la petición. GET los envía en la URL (query string). POST se usa para formularios, subida de archivos y creación de recursos en APIs REST.' },
    { tema:'UF2', p:'¿Qué versión de HTTP añadió multiplexación y Server Push?', ops:['HTTP/1.0','HTTP/1.1','HTTP/2','HTTP/3'], r:2, e:'HTTP/2 introdujo multiplexación (varias peticiones simultáneas en una conexión TCP), compresión de cabeceras (HPACK) y Server Push (enviar recursos proactivamente).' },
  ],

  // ─────────────────────────────────────────────────────────
  // UF3 — SERVIDORES DE APLICACIONES
  // Java EE · Apache Tomcat · Servlets · JSP · Sesiones
  // ─────────────────────────────────────────────────────────
  UF3: [
    { tema:'UF3', p:'¿Cuál es una desventaja del uso de servidores de aplicaciones?', ops:['Facilidad en la administración de actualizaciones','La menor necesidad de servidores potentes','La disminución de la administración de clientes','El incremento de la superficie de ataque, ya que se transmite información por la red'], r:3, e:'Al centralizar la aplicación, toda la comunicación pasa por la red, ampliando la superficie de ataque. También, si el servidor cae, todos los clientes quedan sin servicio.' },
    { tema:'UF3', p:'¿Para qué sirven las variables CATALINA_HOME y CATALINA_BASE en Tomcat?', ops:['Para almacenar los archivos temporales de la JVM','Para contener los elementos comunes a todas las instancias','Apuntan al directorio raíz de una única instalación','Permiten ejecutar varias instancias de Tomcat en una máquina apuntando al mismo directorio de instalación'], r:3, e:'CATALINA_HOME apunta al directorio de instalación de Tomcat. CATALINA_BASE permite que varias instancias compartan esa instalación con configuraciones independientes.' },
    { tema:'UF3', p:'¿Cuál de estas NO es una edición de la plataforma Java de Oracle?', ops:['Java Enterprise Edition (Java EE)','Java Micro Edition (Java ME)','Java Standard Edition (Java SE)','Java Microservice Edition (Java MSE)'], r:3, e:'Las ediciones oficiales son Java SE (escritorio/servidor básico), Java EE/Jakarta EE (empresarial) y Java ME (dispositivos embebidos). Java MSE no existe.' },
    { tema:'UF3', p:'¿Cuál es la diferencia principal entre cookies y sesiones en Java?', ops:['Las cookies almacenan datos en el servidor; las sesiones en el cliente','No hay diferencia, ambas almacenan en el servidor','Las sesiones almacenan información en el servidor; las cookies lo hacen en el cliente (navegador)','Las cookies son más seguras que las sesiones siempre'], r:2, e:'Cookies: datos en el cliente (navegador), enviadas en cada petición HTTP. Sesiones: datos en el servidor, identificadas por un ID de sesión en una cookie o URL.' },
    { tema:'UF3', p:'¿Qué medida de seguridad recomienda el temario para Tomcat?', ops:['Activar todas las aplicaciones de ejemplo incluidas en la instalación','No es necesario eliminar referencias a la versión de Tomcat','Deshabilitar el security manager siempre','Eliminar toda referencia a la versión de Tomcat para dificultar el uso de exploits'], r:3, e:'Ocultar la versión de Tomcat en cabeceras y páginas de error es una práctica básica de seguridad para dificultar que los atacantes identifiquen vulnerabilidades conocidas.' },
    { tema:'UF3', p:'¿Qué ventaja ofrecen los servidores de aplicaciones frente a un modelo descentralizado?', ops:['Una mayor superficie de ataque del sistema','La necesidad de servidores menos potentes','Una menor protección de la información en tránsito','La disminución de la administración de los clientes'], r:3, e:'Al centralizar la aplicación, los clientes no necesitan software instalado ni mantenimiento local. Solo necesitan un navegador. Reduce enormemente la administración cliente.' },
    { tema:'UF3', p:'¿Qué función tiene el archivo web.xml en una aplicación web en Tomcat?', ops:['Contiene las páginas HTML y JavaScript de la aplicación','Define las librerías externas necesarias','Se usa para almacenar archivos temporales','Describe los servlets y componentes de la aplicación, con parámetros de inicialización y restricciones de seguridad'], r:3, e:'web.xml es el descriptor de despliegue (Deployment Descriptor) de una aplicación Java EE. Define servlets, mappings de URL, filtros, parámetros de contexto y seguridad.' },
    { tema:'UF3', p:'¿Cómo se gestionan las cookies en Java/Servlets?', ops:['Con la clase SessionCookie del paquete javax.servlet.session','Con la interfaz HttpRequest y sus métodos addCookie y getCookie','Con la clase Cookie del paquete javax.servlet.http, con constructor nombre/valor y métodos como setValue','Con la clase ServletCookie del paquete jakarta.servlet'], r:2, e:'La clase javax.servlet.http.Cookie permite crear cookies con new Cookie(nombre, valor), configurarlas con setMaxAge(), setPath() y añadirlas con response.addCookie().' },
    { tema:'UF3', p:'¿Cuál es el nombre del contenedor de servlets de Apache Tomcat desde la versión 4.x?', ops:['Jasper','Tomcat Engine','JSP','Catalina'], r:3, e:'Catalina es el contenedor de servlets de Apache Tomcat (desde v4). Jasper es el motor JSP de Tomcat. Ambos son componentes del mismo servidor.' },
    { tema:'UF3', p:'¿Qué contiene la capa de datos en la arquitectura de plataformas Java?', ops:['La lógica de negocio de la aplicación','La interfaz de usuario (navegador o app)','Los servicios que proporcionan acceso a la información almacenada, normalmente en una base de datos','Los servlets que procesan las peticiones HTTP'], r:2, e:'La arquitectura Java EE tiene 4 capas: cliente, presentación, servicios de negocio y datos. La capa de datos gestiona la persistencia (JDBC, JPA, bases de datos).' },
    { tema:'UF3', p:'¿Cuál es la diferencia entre Apache Tomcat y Apache TomEE?', ops:['Tomcat y TomEE son exactamente iguales','Tomcat implementa todas las especificaciones Jakarta EE; TomEE solo algunas','Tomcat es una implementación de código abierto de algunas especificaciones Jakarta EE pero no es un servidor de aplicaciones completo; TomEE sí lo es','TomEE es más ligero que Tomcat'], r:2, e:'Tomcat es un contenedor de servlets/JSP (implementación parcial de Jakarta EE). TomEE añade soporte completo para CDI, EJB, JPA, etc., convirtiéndose en servidor de aplicaciones completo.' },
    { tema:'UF3', p:'¿Para qué sirven las sesiones en Java?', ops:['Para enviar información que el usuario ha pedido de una base de datos','Para almacenar pequeñas cantidades de información en el navegador','Para recibir información del usuario y almacenarla en base de datos','Para identificar y almacenar información sobre los usuarios cuando realizan varias peticiones al mismo servidor'], r:3, e:'Las sesiones permiten mantener estado entre peticiones HTTP (que es un protocolo sin estado). HttpSession almacena objetos en el servidor asociados a un usuario.' },
    { tema:'UF3', p:'¿Qué hace la capa de presentación en la arquitectura Java?', ops:['Ejecutar elementos en la máquina cliente','Proporcionar acceso a la información almacenada en una base de datos','Procesar las peticiones de la capa de servicios de negocios','Transformar la información a un formato legible para el cliente, generalmente HTML'], r:3, e:'La capa de presentación (JSP, Thymeleaf, servlets) genera la respuesta visual: convierte datos del modelo en HTML, JSON u otro formato que el cliente pueda consumir.' },
    { tema:'UF3', p:'¿Cuál es la naturaleza de Apache Tomcat?', ops:['Es un servidor de aplicaciones libre','Es un contenedor de servlets propietario','Es un servidor de aplicaciones propietario','Es un contenedor de servlets libre'], r:3, e:'Apache Tomcat es un contenedor de servlets y JSP de código abierto (Apache License). No es un servidor de aplicaciones completo, ya que no implementa todas las especificaciones Jakarta EE.' },
    { tema:'UF3', p:'Tras modificar un archivo .java y compilarlo a .class, ¿qué acción se usa en el gestor de Tomcat para aplicar los cambios sin reiniciar?', ops:['Arrancar','Parar','Replegar','Recargar'], r:3, e:'Recargar (Reload) en el gestor de aplicaciones de Tomcat recarga la aplicación web, liberando caché y aplicando los nuevos archivos .class sin reiniciar todo Tomcat.' },
    { tema:'UF3', p:'¿Qué es Java bytecode?', ops:['El código máquina generado directamente para Windows','Un código intermedio generado por el compilador Java que la JVM interpreta','El código fuente Java antes de compilar','Un tipo especial de código C++ compatible con Java'], r:1, e:'Java compila a bytecode (archivos .class), un código intermedio independiente de la plataforma. La JVM de cada sistema operativo interpreta ese bytecode, permitiendo "compilar una vez, ejecutar en cualquier parte".' },
    { tema:'UF3', p:'¿Qué es la JVM?', ops:['El compilador de Java','El IDE oficial de Oracle para Java','La máquina virtual de Java que interpreta el bytecode y lo ejecuta en cualquier plataforma','Un servidor de aplicaciones Java'], r:2, e:'JVM (Java Virtual Machine) interpreta el bytecode Java y lo ejecuta en el hardware específico. Cada SO tiene su JVM, pero el mismo bytecode funciona en todas.' },
  ],

  // ─────────────────────────────────────────────────────────
  // UF4 — TRANSFERENCIA DE ARCHIVOS
  // FTP · FTPS · SFTP · SSH · FileZilla
  // ─────────────────────────────────────────────────────────
  UF4: [
    { tema:'UF4', p:'¿Cuántos canales de conexión usa el protocolo FTP?', ops:['Uno: canal de datos','Dos: canal de control (comandos) y canal de datos','Tres: control, datos y seguridad','Uno: canal de control únicamente'], r:1, e:'FTP usa dos conexiones TCP separadas: el canal de control (puerto 21) para comandos y respuestas, y el canal de datos (puerto 20 en modo activo) para la transferencia.' },
    { tema:'UF4', p:'¿Cuál es la diferencia entre el modo activo y el modo pasivo en FTP?', ops:['En modo activo, el servidor conecta al cliente para el canal de datos; en modo pasivo, el cliente conecta al servidor','Son idénticos, es solo una nomenclatura diferente','En modo pasivo, el servidor inicia siempre ambas conexiones','En modo activo, el cliente inicia ambas conexiones'], r:0, e:'Modo activo: el servidor abre conexión de datos hacia el cliente (problemático con NAT/firewall). Modo pasivo: el cliente inicia también la conexión de datos, más compatible con firewalls.' },
    { tema:'UF4', p:'¿Qué protocolo de transferencia de archivos cifra la comunicación usando SSH?', ops:['FTP','FTPS','SFTP','SCP únicamente'], r:2, e:'SFTP (SSH File Transfer Protocol) transfiere archivos sobre una conexión SSH cifrada. A pesar del nombre, no es una extensión de FTP sino un protocolo independiente.' },
    { tema:'UF4', p:'¿Qué hace el protocolo FTPS?', ops:['Es igual que SFTP pero más antiguo','Es FTP con cifrado TLS/SSL añadido','Es un protocolo basado en SSH para transferencia segura','Es una versión de FTP que solo funciona en redes locales'], r:1, e:'FTPS (FTP over TLS/SSL) añade cifrado TLS al protocolo FTP estándar. Definido en la RFC 4217. Distinto de SFTP, que es un protocolo diferente basado en SSH.' },
    { tema:'UF4', p:'¿Qué cliente de FTP multiplataforma es ampliamente usado e incluye interfaz gráfica?', ops:['WinSCP','Cyberduck','FileZilla','PuTTY'], r:2, e:'FileZilla es uno de los clientes FTP/FTPS/SFTP más populares. Tiene versión de escritorio (gráfica) y también versión servidor. Es multiplataforma y gratuito.' },
    { tema:'UF4', p:'¿Qué permite el acceso anónimo en FTP?', ops:['Acceso sin usuario ni contraseña para descargar archivos públicos','Acceso con el usuario "root" sin contraseña','Acceso cifrado sin autenticación','Acceso con cualquier contraseña válida del sistema'], r:0, e:'El acceso anónimo FTP permite que usuarios sin cuenta descarguen archivos públicos usando "anonymous" como usuario y cualquier email como contraseña. Útil para distribución pública.' },
    { tema:'UF4', p:'¿Qué es SSHFS?', ops:['Un tipo de servidor FTP basado en SSH','Un sistema de archivos que permite montar directorios remotos de forma local a través de SSH','Un protocolo de cifrado para FTPS','Una herramienta de auditoría SSH'], r:1, e:'SSHFS (SSH FileSystem) permite montar un directorio remoto como si fuera local, usando SFTP/SSH como transporte. El usuario puede trabajar con archivos remotos con sus aplicaciones locales.' },
    { tema:'UF4', p:'¿Qué protocolo usa el puerto 21 por defecto?', ops:['SFTP','SSH','FTPS','FTP (canal de control)'], r:3, e:'FTP usa el puerto 21 para el canal de control (comandos). El canal de datos usa el puerto 20 en modo activo. SSH/SFTP usan el puerto 22.' },
    { tema:'UF4', p:'¿Cuál es la principal diferencia de seguridad entre FTP y SFTP?', ops:['FTP es más seguro porque usa dos canales','SFTP cifra tanto los datos como las credenciales; FTP transmite todo en texto plano','FTP usa TLS; SFTP usa algoritmos propietarios','No hay diferencia de seguridad entre ambos'], r:1, e:'FTP transmite usuario, contraseña y datos en texto plano (interceptable con sniffers). SFTP cifra toda la comunicación dentro del túnel SSH.' },
    { tema:'UF4', p:'¿Qué servidor FTP libre se menciona en el temario para instalación en Linux?', ops:['ProFTPD','vsftpd','PureFTPD','FileZilla Server'], r:1, e:'vsftpd (Very Secure FTP Daemon) es el servidor FTP recomendado en el temario. Es ligero, seguro y ampliamente usado en sistemas Linux.' },
    { tema:'UF4', p:'¿Qué es OpenSSH?', ops:['Un protocolo de transferencia de archivos propietario','Una implementación libre del protocolo SSH que incluye cliente y servidor SSH, además de soporte SFTP','Un servidor web alternativo a Apache','Un sistema de gestión de certificados SSL'], r:1, e:'OpenSSH es la implementación libre más popular de SSH. Incluye el servidor sshd, el cliente ssh, scp y sftp. Viene instalado por defecto en la mayoría de distribuciones Linux.' },
    { tema:'UF4', p:'¿Qué tipo de datos puede transferir FTP?', ops:['Solo archivos de texto ASCII','Solo archivos binarios','Archivos en modo ASCII (texto) o binario, según configuración','Solo archivos menores de 4GB'], r:2, e:'FTP admite dos modos de transferencia: ASCII (para archivos de texto, convierte saltos de línea) y binario (para cualquier tipo de archivo sin conversión). Hay que elegir el modo correcto.' },
    { tema:'UF4', p:'¿Cuál es el protocolo indicado para entornos donde hay NAT o firewalls que bloquean conexiones entrantes?', ops:['FTP en modo activo','FTP en modo pasivo','Telnet','TFTP'], r:1, e:'El modo pasivo FTP es el recomendado cuando el cliente está detrás de NAT o firewall, ya que el cliente es quien inicia ambas conexiones (no hay conexión entrante al cliente).' },
  ],

  // ─────────────────────────────────────────────────────────
  // UF5 — DOCUMENTACIÓN Y CONTROL DE VERSIONES
  // Git · GitHub · Javadoc · MediaWiki · Man · CI/CD
  // ─────────────────────────────────────────────────────────
  UF5: [
    { tema:'UF5', p:'¿Por qué es tan habitual encontrar software sin documentar?', ops:['Porque las herramientas de documentación son muy caras','Porque los usuarios ya conocen el software y no necesitan manuales','Porque requiere personal externo y es muy costoso','Porque falta tiempo, no se le da la importancia que merece y documentar tiene fama de ser un trabajo aburrido'], r:3, e:'Las razones más comunes son: plazos ajustados, cultura empresarial que no valora la documentación y percepción entre los desarrolladores de que es un trabajo tedioso.' },
    { tema:'UF5', p:'¿Cuáles son las fases del ciclo de vida del software según el temario?', ops:['Análisis, diseño, programación, pruebas, despliegue y mantenimiento','Recogida de requisitos, diseño, implementación, prueba, despliegue y mantenimiento','Recogida y análisis de requerimientos, especificación, implementación, comprobación, despliegue y mantenimiento','Planificación, desarrollo, QA y producción'], r:2, e:'El ciclo de vida incluye: recogida y análisis de requerimientos → especificación → implementación/desarrollo → comprobación → despliegue → mantenimiento.' },
    { tema:'UF5', p:'¿Cuál es una característica importante de los comentarios Javadoc en Java?', ops:['Deben comenzar con "//" y tener máximo 100 caracteres','Deben comenzar con "/*" y terminar con "*/"','Deben contener un primer bloque de descripción seguido de etiquetas precedidas por "@"','Solo documentan clases, no métodos ni parámetros'], r:2, e:'Los comentarios Javadoc (/** ... */) contienen: descripción del elemento y etiquetas @param, @return, @throws, @author, @version, etc. La herramienta javadoc genera HTML a partir de ellos.' },
    { tema:'UF5', p:'¿Para qué sirve el control de versiones?', ops:['Solo para indicar al usuario la versión instalada','Solo en la fase de diseño para contar propuestas','Para tener un registro de los cambios realizados a lo largo de la vida útil de un programa','Solo en la fase de pruebas para anotar los fallos'], r:2, e:'El control de versiones registra todos los cambios: quién hizo qué, cuándo y por qué. Permite volver a versiones anteriores, trabajar en paralelo y colaborar en equipo.' },
    { tema:'UF5', p:'¿Qué áreas de trabajo utiliza Git?', ops:['Solo el repositorio','Solo el directorio de trabajo y el repositorio','Solo el área de preparación y el repositorio','El directorio de trabajo, el área de preparación (staging) y el repositorio'], r:3, e:'Git tiene tres áreas: directorio de trabajo (archivos editados), staging/índice (cambios preparados con git add) y repositorio (historial de commits con git commit).' },
    { tema:'UF5', p:'¿Con qué comando de Git se eliminan archivos del directorio de trabajo y del área de preparación?', ops:['action_delete','action_remove','reset','git rm'], r:3, e:'git rm elimina el archivo del directorio de trabajo y lo marca para eliminación en el próximo commit. git rm --cached lo elimina solo del staging, manteniendo el archivo local.' },
    { tema:'UF5', p:'¿Cuál es la utilidad principal de la herramienta Man en sistemas Unix?', ops:['Facilitar el desarrollo colaborativo de documentación','Proporcionar una interfaz gráfica para los manuales','Permitir la edición colaborativa de wikis','Ofrecer una interfaz de línea de comandos para acceder a los manuales de referencia del sistema'], r:3, e:'Man (manual) es el sistema de ayuda de Unix/Linux. Desde la terminal: "man comando" muestra la página de manual con descripción, opciones y ejemplos de uso.' },
    { tema:'UF5', p:'¿Qué ventaja ofrece MediaWiki como plataforma de documentación?', ops:['Permite generar documentación en HTML a partir de Java','Proporciona interfaz gráfica para manuales del sistema','Facilita la creación colaborativa y centralizada de documentación multilenguaje, actualizable y fiable','Solo sirve para documentar código fuente'], r:2, e:'MediaWiki (el software detrás de Wikipedia) permite que múltiples usuarios colaboren en la documentación, con historial de cambios, búsqueda y organización en categorías.' },
    { tema:'UF5', p:'¿Cuál es el propósito principal de la integración continua (CI) en GitHub?', ops:['Publicar nuevas versiones del producto inmediatamente después de su desarrollo','Detectar conflictos y realizar pruebas manualmente en cada cambio','Realizar pruebas e integrar automáticamente los cambios de programación en un repositorio compartido','Gestionar el acceso de los colaboradores al repositorio'], r:2, e:'CI automatiza: al hacer push, se ejecutan automáticamente los tests, análisis de código y build. Si algo falla, se notifica inmediatamente antes de que llegue a producción.' },
    { tema:'UF5', p:'¿Qué sección de los manuales de Man está reservada para los programas ejecutables y órdenes del shell?', ops:['Sección 2','Sección 5','Sección 4','Sección 1'], r:3, e:'La sección 1 de Man contiene comandos de usuario y shell. Sección 2: llamadas al sistema. Sección 3: funciones de biblioteca. Sección 5: formatos de archivo. Sección 8: comandos de administración.' },
    { tema:'UF5', p:'¿Cuál es una ventaja de trabajar con ramas (branches) en Git?', ops:['Facilita la creación de repositorios distribuidos','Permite eliminar los conflictos entre programadores','Permite eliminar el historial de cambios antiguo','Permite trabajar en paralelo en diferentes funcionalidades sin afectar a la rama principal'], r:3, e:'Las ramas permiten desarrollar features, corregir bugs o experimentar de forma aislada. Solo se fusionan (merge) a main/master cuando están probadas y aprobadas.' },
    { tema:'UF5', p:'¿Qué debe contener siempre el repositorio en un sistema de control de versiones?', ops:['Solo los archivos de código fuente, sin historial','Una copia por cada desarrollador del equipo','La última versión válida del programa','Solo los archivos modificados en el último sprint'], r:2, e:'El repositorio central debe contener siempre la última versión estable y funcional. Los desarrolladores trabajan en ramas y solo integran cuando el código pasa las pruebas.' },
    { tema:'UF5', p:'¿Por qué es importante estructurar adecuadamente la documentación del software?', ops:['Para evitar errores en el código y mejorar la seguridad','Para hacerla más atractiva visualmente','Para que sea entendible y útil para el público objetivo, localizar información rápido y conseguir documentación homogénea','Para reducir el tiempo de redacción'], r:2, e:'Una buena estructura documental: índice claro, secciones bien organizadas, ejemplos contextualizados y formato estándar, permiten a cualquier persona encontrar y entender la información.' },
    { tema:'UF5', p:'¿Cómo se indica en wikitexto (MediaWiki) que un texto debe aparecer en negrita?', ops:["== Texto ==","=== Texto ===","''Texto''","'''Texto'''"], r:3, e:"En wikitexto: '''texto''' = negrita, ''texto'' = cursiva, == Texto == = título de sección nivel 2, === Texto === = subsección nivel 3." },
    { tema:'UF5', p:'¿Qué comando Git se usa para crear un nuevo commit con los cambios del área de preparación?', ops:['git push','git add','git commit -m "mensaje"','git merge'], r:2, e:'git commit -m "mensaje" crea un snapshot permanente de los cambios en staging. git add mueve cambios al staging. git push sube commits al repositorio remoto.' },
    { tema:'UF5', p:'¿Qué es un repositorio remoto en Git?', ops:['Una copia local del proyecto en otro disco duro','Una versión cifrada del repositorio local','Un repositorio alojado en un servidor (GitHub, GitLab, Bitbucket) que sirve de punto central de colaboración','Una rama especial del repositorio'], r:2, e:'El repositorio remoto (origin) está en un servidor accesible por el equipo. git push sube cambios, git pull los descarga. GitHub/GitLab alojan repositorios remotos.' },
    { tema:'UF5', p:'¿Qué hace git clone?', ops:['Crea una nueva rama en el repositorio','Descarga una copia completa de un repositorio remoto, incluyendo todo el historial','Solo descarga los últimos cambios del repositorio remoto','Fusiona dos ramas del repositorio'], r:1, e:'git clone crea una copia local completa del repositorio remoto: todos los archivos, todas las ramas y todo el historial de commits. Es el punto de partida para colaborar.' },
    { tema:'UF5', p:'¿Qué es un Pull Request (PR) en GitHub?', ops:['Una solicitud para descargar cambios del repositorio remoto','Un mecanismo para proponer la fusión de cambios de una rama en otra, con revisión de código','Una forma de reportar bugs en el código','Una operación para revertir commits anteriores'], r:1, e:'Un PR propone fusionar cambios de una rama (feature branch) en otra (main). Permite revisión de código, comentarios y aprobación por parte del equipo antes de hacer el merge.' },
  ],

};

const UFS = [
  { id: 'UF1', nombre: 'DNS y dominios' },
  { id: 'UF2', nombre: 'Servidores web (Apache/Nginx)' },
  { id: 'UF3', nombre: 'FTP, SSH y acceso remoto' },
  { id: 'UF4', nombre: 'Docker y contenedores' },
  { id: 'UF5', nombre: 'CI/CD y despliegue cloud' },
];

// ── Preguntas extra para completar 30 por UF ─────────────────────
const EXTRA_DESP = {
  UF1: [
    { tema:'UF1', p:'¿Qué tipo de registro DNS se usa para aliases (nombres alternativos) de un dominio?', ops:['A','MX','CNAME','NS'], r:2, e:'CNAME (Canonical Name) crea un alias que apunta a otro nombre de dominio. Ejemplo: www.ejemplo.com → ejemplo.com. No puede usarse en el apex del dominio (raíz); ahí se usa ALIAS o ANAME.' },
    { tema:'UF1', p:'¿Cuál es el TTL en DNS y qué efecto tiene un valor bajo?', ops:['Time To Live: tiempo en segundos que los resolvers cachean el registro. Un TTL bajo propaga los cambios más rápido pero genera más tráfico DNS','El tiempo máximo de resolución de una petición DNS','El número de saltos máximos de un paquete DNS','El tiempo de validez de un certificado SSL'], r:0, e:'TTL bajo (ej. 300s) hace que los cambios en DNS propaguen en minutos, útil antes de migraciones. TTL alto (ej. 86400s = 1 día) reduce consultas al servidor autoritativo pero retrasa la propagación de cambios.' },
    { tema:'UF1', p:'¿Qué herramienta de línea de comandos permite consultar registros DNS de forma detallada?', ops:['ping','traceroute','dig','nslookup'], r:2, e:'dig (Domain Information Groper) es la herramienta estándar para consultas DNS detalladas. Ejemplo: dig ejemplo.com A, dig ejemplo.com MX, dig @8.8.8.8 ejemplo.com. Muestra el registro, TTL, servidor autoritativo y tiempos.' },
    { tema:'UF1', p:'¿Qué es un servidor DNS recursivo?', ops:['Un servidor que almacena la zona DNS de un dominio','Un servidor que resuelve nombres consultando otros servidores DNS en nombre del cliente, cacheando las respuestas','Un servidor que solo responde consultas de su propia zona','Un servidor DNS de respaldo'], r:1, e:'El resolver recursivo (Google 8.8.8.8, Cloudflare 1.1.1.1) hace el trabajo por el cliente: pregunta a los root servers, luego a los TLD, luego al autoritativo, y devuelve la respuesta final al cliente.' },
    { tema:'UF1', p:'¿Qué es DNSSEC y qué protege?', ops:['Un protocolo de transferencia de zonas DNS cifrado','Una extensión de seguridad que firma criptográficamente los registros DNS para prevenir envenenamiento de caché y spoofing','Un sistema de backup de registros DNS','Un protocolo DNS sobre HTTPS'], r:1, e:'DNSSEC añade firmas digitales a los registros DNS. El resolver verifica que la respuesta viene del servidor autoritativo legítimo y no ha sido manipulada. Protege contra DNS cache poisoning y ataques MitM en la resolución DNS.' },
    { tema:'UF1', p:'¿Qué registro DNS indica el servidor de correo para un dominio?', ops:['A','CNAME','MX','TXT'], r:2, e:'El registro MX (Mail Exchange) especifica el servidor de correo del dominio y su prioridad. Múltiples registros MX con diferentes prioridades (menor número = mayor prioridad) permiten redundancia en la recepción de correo.' },
    { tema:'UF1', p:'¿Qué es un dominio de tercer nivel y pon un ejemplo?', ops:['www.ejemplo.com — www es el tercer nivel','mail.empresa.ejemplo.com — mail es el tercer nivel','ejemplo.com — ejemplo es el tercer nivel','ejemplo.co.uk — co es el tercer nivel'], r:1, e:'La jerarquía DNS: TLD (.com), segundo nivel (ejemplo.com), tercer nivel (mail.empresa.ejemplo.com). www.ejemplo.com es técnicamente tercer nivel aunque se trate como "dominio principal". mail.empresa.com es un subdominio de tercer nivel.' },
    { tema:'UF1', p:'¿Qué es la propagación DNS y cuánto puede tardar?', ops:['El proceso de registrar un dominio nuevo, que tarda 24h','El tiempo que tardan los resolvers de todo el mundo en actualizar su caché con los nuevos registros DNS, típicamente entre minutos y 48h','El proceso de transferir un dominio entre registradores','La sincronización entre servidores DNS primario y secundario'], r:1, e:'Cuando cambias registros DNS, los resolvers del mundo siguen usando la versión cacheada hasta que expira el TTL. La "propagación" no es simultánea: algunos resolvers actualizan en minutos, otros pueden tardar hasta 48h si tenían el registro cacheado con TTL alto.' },
  ],
  UF2: [
    { tema:'UF2', p:'¿Qué hace la directiva ServerName en Apache?', ops:['Define el nombre del proceso httpd','Establece el nombre de host y puerto que el servidor usa para identificarse a sí mismo, esencial para Virtual Hosts','Configura el log de acceso del servidor','Define el usuario con el que Apache ejecuta los procesos'], r:1, e:'ServerName especifica el hostname principal del servidor (ServerName www.ejemplo.com). En VirtualHosts, cada bloque tiene su propio ServerName para que Apache sepa qué configuración aplicar a cada dominio.' },
    { tema:'UF2', p:'¿Qué directiva Apache define el directorio raíz de los archivos web?', ops:['RootDir','WebRoot','DocumentRoot','ServerRoot'], r:2, e:'DocumentRoot /var/www/html define dónde están los archivos web que Apache sirve. ServerRoot define donde están los archivos de configuración de Apache (distinto). Cada VirtualHost puede tener su propio DocumentRoot.' },
    { tema:'UF2', p:'¿Qué es .htaccess en Apache?', ops:['El archivo de contraseñas de acceso HTTP básico','Un archivo de configuración a nivel de directorio que sobrescribe la configuración global de Apache para ese directorio','El log de acceso de Apache','El archivo de hosts virtuales de Apache'], r:1, e:'.htaccess permite configuración por directorio sin reiniciar Apache: redireccionamientos, reescritura de URLs (mod_rewrite), autenticación básica, control de acceso por IP. Requiere AllowOverride en la configuración principal.' },
    { tema:'UF2', p:'¿Qué módulo Apache habilita la reescritura de URLs?', ops:['mod_ssl','mod_rewrite','mod_deflate','mod_headers'], r:1, e:'mod_rewrite permite transformar URLs con reglas regex. Fundamental para URLs limpias en frameworks (index.php?page=home → /home). Se habilita con a2enmod rewrite. Usa RewriteRule y RewriteCond en httpd.conf o .htaccess.' },
    { tema:'UF2', p:'¿Qué diferencia principal hay entre Apache y Nginx en su arquitectura?', ops:['Nginx no soporta PHP; Apache sí','Apache usa un proceso/hilo por conexión; Nginx usa un modelo event-driven asíncrono, siendo más eficiente con muchas conexiones concurrentes','Apache es más rápido para contenido estático; Nginx para dinámico','No hay diferencia arquitectural relevante'], r:1, e:'Apache (prefork/worker): cada conexión usa un proceso o hilo. Nginx: un solo proceso maneja miles de conexiones con E/S asíncrona. Nginx escala mejor bajo alta carga concurrente y usa menos memoria. Apache es más flexible con módulos.' },
    { tema:'UF2', p:'¿Qué es un Virtual Host en Apache/Nginx?', ops:['Una máquina virtual que ejecuta Apache','La configuración que permite servir múltiples sitios web (dominios) desde un único servidor con una sola IP','Un servidor Apache en contenedor Docker','Un servidor de respaldo para alta disponibilidad'], r:1, e:'Virtual Hosts permiten alojar n dominios en un servidor. Apache: <VirtualHost *:80> con ServerName diferente. Nginx: server { } con server_name. El servidor enruta cada petición al VirtualHost correcto según la cabecera Host.' },
    { tema:'UF2', p:'¿Qué comando de Apache habilita un sitio (virtual host) en sistemas Debian/Ubuntu?', ops:['apache2ctl enable-site ejemplo.conf','a2ensite ejemplo.conf','httpd --enable ejemplo','service apache2 add-site ejemplo'], r:1, e:'a2ensite ejemplo.conf crea un symlink en sites-enabled/ apuntando al archivo en sites-available/. Luego apache2ctl configtest verifica la sintaxis y service apache2 reload recarga la configuración sin reiniciar.' },
    { tema:'UF2', p:'¿Qué es Let\'s Encrypt y qué herramienta lo integra con Apache/Nginx?', ops:['Una CA de pago que emite certificados EV','Una CA gratuita y automatizada que emite certificados TLS/SSL. Certbot automatiza su instalación y renovación en Apache y Nginx','Un protocolo de cifrado alternativo a TLS','Un servicio de auditoría de certificados SSL'], r:1, e:"Let's Encrypt emite certificados TLS gratuitos con validez de 90 días. Certbot (EFF) automatiza la obtención, instalación en Apache/Nginx y renovación automática (certbot renew). Democratizó el HTTPS para toda la web." },
    { tema:'UF2', p:'¿Qué es el protocolo HTTP/2 y qué mejoras aporta sobre HTTP/1.1?', ops:['Es idéntico a HTTP/1.1 con cifrado','Permite multiplexación (múltiples peticiones en paralelo por una sola conexión), compresión de cabeceras y server push','Solo funciona sobre HTTP, no sobre HTTPS','Elimina el uso de cookies para mejorar el rendimiento'], r:1, e:'HTTP/2 resuelve el head-of-line blocking de HTTP/1.1: multiplexación = N peticiones en paralelo en 1 conexión TCP. Header compression (HPACK) reduce el overhead. Server push = el servidor envía recursos antes de que el cliente los pida.' },
    { tema:'UF2', p:'¿Qué significa el código de estado HTTP 301?', ops:['El recurso no fue encontrado','El servidor tuvo un error interno','Redirección permanente — el recurso ha sido movido definitivamente a otra URL','El acceso requiere autenticación'], r:2, e:'301 Moved Permanently indica que el recurso ha cambiado de URL de forma permanente. El navegador y los buscadores actualizan sus registros. 302 Found es temporal. Para SEO: usar 301 al cambiar URLs de producción.' },
    { tema:'UF2', p:'¿Qué es la compresión gzip/brotli en servidores web?', ops:['Un sistema de cifrado de respuestas HTTP','La compresión de las respuestas HTTP antes de enviarlas al cliente, reduciendo el tamaño hasta un 70-90% y acelerando la carga','Un sistema de caché de archivos estáticos','Un protocolo de transferencia de archivos comprimidos'], r:1, e:'mod_deflate (Apache) o gzip/brotli (Nginx) comprimen las respuestas de texto (HTML, CSS, JS, JSON) antes de enviarlas. El cliente las descomprime. Brotli es el algoritmo moderno de Google, más eficiente que gzip para web.' },
    { tema:'UF2', p:'¿Qué es la directiva Alias en Apache?', ops:['Un sinónimo para ServerName','Mapea una URL a un directorio del sistema de archivos diferente al DocumentRoot','Un tipo de Virtual Host','Un registro DNS interno de Apache'], r:1, e:'Alias /static /var/www/assets hace que las peticiones a /static/* se sirvan desde /var/www/assets/*. Útil para servir archivos de diferentes ubicaciones del sistema bajo una misma URL.' },
  ],
  UF3: [
    { tema:'UF3', p:'¿Qué es la autenticación basada en clave pública en SSH?', ops:['Usar la clave pública del servidor para cifrar la contraseña','El cliente genera un par de claves; la pública se añade al servidor en authorized_keys; el servidor autentica sin contraseña','Una técnica de autenticación que usa certificados SSL','Un sistema de autenticación de dos factores con SMS'], r:1, e:'La autenticación por clave SSH: ssh-keygen genera el par (id_rsa + id_rsa.pub). La clave pública se añade al ~/.ssh/authorized_keys del servidor. El cliente demuestra tener la clave privada sin enviarla. Más segura que contraseñas.' },
    { tema:'UF3', p:'¿Qué es el archivo known_hosts en SSH?', ops:['El archivo con las claves privadas autorizadas del usuario','Un registro de los hosts SSH a los que nos hemos conectado previamente, con su clave pública para verificar la identidad en futuras conexiones','El archivo de configuración del cliente SSH','El log de conexiones SSH del servidor'], r:1, e:'~/.ssh/known_hosts almacena la huella (fingerprint) de la clave pública de cada servidor al que nos conectamos. En la siguiente conexión, SSH verifica que la huella coincide. Si cambia, alerta de posible MitM.' },
    { tema:'UF3', p:'¿Qué opción del comando ssh permite tunelizar puertos locales a través de una conexión SSH?', ops:['-t (pseudoterminal)','-X (X11 forwarding)','-L (local port forwarding)','-v (verbose)'], r:2, e:'ssh -L 8080:servidor-interno:80 usuario@bastion crea un túnel: las conexiones al puerto 8080 local se reenvían a servidor-interno:80 a través del bastion. Útil para acceder a servicios internos de forma segura.' },
    { tema:'UF3', p:'¿Cuál es la diferencia entre rsync y scp para transferencia de archivos?', ops:['scp solo funciona con archivos binarios; rsync con texto','rsync solo transfiere los cambios (incremental, eficiente para sincronización); scp siempre copia el archivo completo','scp es más rápido para archivos grandes','No hay diferencia práctica entre ambos'], r:1, e:'rsync --checksum o -u solo transfiere los bloques que han cambiado. Ideal para sincronización repetida de directorios grandes. scp siempre copia el archivo completo: más simple pero menos eficiente para sincronizaciones.' },
    { tema:'UF3', p:'¿Qué directiva del archivo sshd_config desactiva el login SSH con contraseña?', ops:['DisablePasswordAuth yes','PasswordAuthentication no','NoPasswordLogin yes','AuthMethod key-only'], r:1, e:'PasswordAuthentication no en /etc/ssh/sshd_config desactiva la autenticación por contraseña, forzando el uso de clave pública. Reduce drásticamente el riesgo de ataques de fuerza bruta. Reiniciar: systemctl restart sshd.' },
    { tema:'UF3', p:'¿Qué hace el comando ssh-copy-id?', ops:['Genera un nuevo par de claves SSH','Copia la clave pública local al archivo authorized_keys del servidor remoto de forma automática y segura','Cambia la contraseña de la clave privada SSH','Revoca una clave SSH en el servidor remoto'], r:1, e:'ssh-copy-id usuario@servidor copia ~/.ssh/id_rsa.pub al ~/.ssh/authorized_keys del servidor con los permisos correctos. Alternativa manual: ssh usuario@servidor "mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys" < ~/.ssh/id_rsa.pub' },
    { tema:'UF3', p:'¿Qué es un servidor SFTP-only en Linux?', ops:['Un servidor FTP con cifrado SSL','Un servidor SSH configurado para permitir solo transferencia de archivos SFTP, sin acceso a shell interactiva, normalmente con chroot al directorio del usuario','Un servidor FTP sin autenticación','Un servidor de archivos SMB con cifrado SSH'], r:1, e:'Configurando Match User sftp_user + ForceCommand internal-sftp + ChrootDirectory en sshd_config se crea un usuario que solo puede transferir archivos por SFTP, sin acceso a shell. Ideal para clientes FTP que necesitan mayor seguridad.' },
    { tema:'UF3', p:'¿Qué son los modos activo y pasivo en FTP y cuál es más compatible con firewalls?', ops:['Activo: el cliente inicia ambas conexiones. Pasivo: el servidor inicia ambas.','Activo: el servidor inicia la conexión de datos al cliente. Pasivo: el cliente inicia ambas conexiones. El pasivo es más compatible con firewalls/NAT.','Ambos modos son igualmente compatibles con firewalls.','Solo el modo activo funciona con IPv6.'], r:1, e:'En FTP activo el servidor conecta de vuelta al cliente para el canal de datos (puerto 20), lo cual los firewalls/NAT del cliente suelen bloquear. En FTP pasivo el cliente inicia ambas conexiones, siendo compatible con NAT y firewalls.' },
    { tema:'UF3', p:'¿Qué hace la opción StrictHostKeyChecking=no en SSH?', ops:['Desactiva el cifrado de la conexión SSH','Permite conectarse sin verificar la huella del host (vulnerable a MitM), útil en scripts de automatización pero inseguro en producción','Desactiva la autenticación por contraseña','Activa el modo verbose de SSH'], r:1, e:'StrictHostKeyChecking=no hace que SSH acepte automáticamente cualquier clave del servidor sin verificar known_hosts. Práctico en CI/CD y aprovisionamiento automático, pero introduce riesgo de MitM. En producción manual: siempre verificar.' },
    { tema:'UF3', p:'¿Qué protocolo usa SFTP como transporte?', ops:['FTP con cifrado SSL/TLS','El protocolo SSH como transporte seguro','Un protocolo propio independiente de SSH y FTP','HTTP/2 con autenticación de clave pública'], r:1, e:'A pesar del nombre, SFTP (SSH File Transfer Protocol) no tiene nada que ver con FTP. Es un subsistema del protocolo SSH. Usa el puerto 22 de SSH. No es FTP sobre SSH, es un protocolo completamente diferente diseñado para SSH.' },
    { tema:'UF3', p:'¿Qué es el Jump Host (bastion host) en SSH?', ops:['Un servidor SSH de alta disponibilidad','Un servidor SSH intermediario que actúa como puente para acceder a servidores en redes privadas sin exposición directa a Internet','Un servidor SSH con autenticación de doble factor','Un servidor proxy HTTP con túnel SSH'], r:1, e:'El bastion host es el único servidor SSH expuesto a Internet. Los servidores internos solo aceptan SSH desde el bastion. Con -J: ssh -J usuario@bastion usuario@servidor-interno. Reduce la superficie de ataque expuesta.' },
    { tema:'UF3', p:'¿Qué es WinSCP?', ops:['Un cliente FTP solo para Windows sin soporte SSH','Un cliente gráfico para Windows que soporta FTP, FTPS, SFTP y SCP con interfaz de dos paneles estilo Norton Commander','Una herramienta de análisis de red para Windows','Un servidor SFTP para Windows'], r:1, e:'WinSCP es el cliente SFTP/FTP más popular en Windows. Interfaz gráfica de dos paneles (local/remoto), soporte SFTP/FTP/FTPS/SCP, integración con PuTTY para sesiones SSH, scripting y automatización.' },
    { tema:'UF3', p:'¿Qué es fail2ban y cómo protege el servidor SSH?', ops:['Un firewall de aplicaciones para proteger servidores web','Un servicio que monitoriza los logs y bloquea automáticamente IPs que acumulan demasiados intentos de login fallidos','Un sistema de detección de intrusos de red','Una herramienta de análisis de vulnerabilidades SSH'], r:1, e:'Fail2ban analiza /var/log/auth.log y cuando detecta N intentos fallidos de SSH en T segundos desde una IP, añade una regla iptables para bloquearla durante X minutos. Mitiga ataques de fuerza bruta automatizados.' },
  ],
  UF4: [
    { tema:'UF4', p:'¿Qué es una imagen Docker?', ops:['Una máquina virtual completa con su propio kernel','Una plantilla de solo lectura con el sistema de archivos y la configuración necesaria para crear contenedores','Una instantánea del estado de un contenedor en ejecución','Un archivo de configuración de Docker Compose'], r:1, e:'Una imagen Docker es inmutable: contiene el SO base, dependencias, código y configuración. Se crea con un Dockerfile. Los contenedores son instancias ejecutables de una imagen. docker pull descarga; docker build crea.' },
    { tema:'UF4', p:'¿Qué diferencia hay entre CMD y ENTRYPOINT en un Dockerfile?', ops:['Son intercambiables, no hay diferencia real','ENTRYPOINT define el ejecutable principal del contenedor (no sobreescribible fácilmente); CMD define argumentos por defecto que sí se pueden sobreescribir','CMD es para comandos de red; ENTRYPOINT para aplicaciones','ENTRYPOINT se ejecuta en build time; CMD en runtime'], r:1, e:'ENTRYPOINT ["node", "app.js"]: el contenedor siempre ejecuta node app.js. CMD ["--port", "3000"]: argumentos por defecto, reemplazables al hacer docker run imagen --port 8080. Juntos: ENTRYPOINT+CMD definen el comando completo.' },
    { tema:'UF4', p:'¿Qué hace docker-compose up -d?', ops:['Construye las imágenes sin iniciar los contenedores','Inicia todos los servicios definidos en docker-compose.yml en modo detached (segundo plano)','Detiene y elimina todos los contenedores','Muestra los logs de todos los contenedores'], r:1, e:'docker compose up -d (o docker-compose up -d) lee el docker-compose.yml, crea las redes y volúmenes necesarios, y arranca todos los servicios en segundo plano. Sin -d, los logs se muestran en el terminal.' },
    { tema:'UF4', p:'¿Qué son los volúmenes en Docker y por qué son importantes?', ops:['Espacios de disco adicionales para las imágenes Docker','Mecanismo para persistir datos fuera del ciclo de vida del contenedor, compartir datos entre contenedores o entre host y contenedor','Una forma de limitar el uso de CPU de los contenedores','El sistema de red virtual de Docker'], r:1, e:'Los datos en un contenedor desaparecen cuando se elimina. Los volúmenes (-v /host:/container o volúmenes nombrados) persisten los datos independientemente del contenedor. Esencial para bases de datos, logs y archivos de usuario.' },
    { tema:'UF4', p:'¿Qué hace el comando docker exec -it contenedor bash?', ops:['Crea un nuevo contenedor basado en la imagen especificada','Abre una sesión interactiva de bash dentro de un contenedor en ejecución','Ejecuta el contenedor en modo interactivo desde el inicio','Muestra los logs del contenedor en tiempo real'], r:1, e:'docker exec -it contenedor bash abre una shell interactiva en el contenedor ya en ejecución. Útil para depuración y diagnóstico. -i mantiene la entrada estándar abierta; -t asigna un pseudo-TTY.' },
    { tema:'UF4', p:'¿Qué es el Docker Registry y qué es Docker Hub?', ops:['El disco duro donde Docker almacena las imágenes locales','Un servidor para almacenar y distribuir imágenes Docker. Docker Hub es el registro público oficial de Docker','El sistema de red de Docker para conectar contenedores','El sistema de logs centralizado de Docker'], r:1, e:'Docker Registry es el servidor que almacena imágenes. Docker Hub (hub.docker.com) es el registro público oficial: millones de imágenes de nginx, postgres, node, etc. También existen registros privados: AWS ECR, GitLab Registry, Harbor.' },
    { tema:'UF4', p:'¿Qué instrucción Dockerfile copia archivos del host a la imagen?', ops:['MOVE','ADD y COPY (COPY es preferido para archivos locales simples)','INCLUDE','IMPORT'], r:1, e:'COPY src dst copia archivos del contexto de build a la imagen. ADD hace lo mismo pero también descomprime archivos .tar y puede copiar desde URLs. La recomendación oficial es usar COPY salvo que necesites las funcionalidades extra de ADD.' },
    { tema:'UF4', p:'¿Qué es una red bridge en Docker?', ops:['Una conexión entre el host y una red externa','La red virtual por defecto que Docker crea para aislar contenedores del mismo host, permitiendo comunicación entre ellos por nombre de servicio','Un tipo de balanceador de carga Docker','Una red de alta velocidad entre contenedores en diferentes hosts'], r:1, e:'La red bridge crea un switch virtual privado. Los contenedores de la misma red bridge se comunican entre sí por nombre (sin IP). Los contenedores están aislados del host y de otras redes. En docker-compose, cada proyecto tiene su red bridge automática.' },
    { tema:'UF4', p:'¿Qué es Docker Compose y para qué se usa?', ops:['Una herramienta gráfica para gestionar imágenes Docker','Una herramienta para definir y ejecutar aplicaciones multi-contenedor con un archivo YAML (docker-compose.yml)','Un registro de imágenes Docker privado','Un sistema de orquestación de contenedores a gran escala'], r:1, e:'Docker Compose define en un YAML todos los servicios de la app (web, db, redis, nginx) con sus configuraciones: imagen, puertos, volúmenes, redes, variables de entorno. docker compose up arranca todo el stack con un comando.' },
    { tema:'UF4', p:'¿Qué diferencia hay entre Docker y una máquina virtual?', ops:['No hay diferencia funcional entre ambos','Docker comparte el kernel del host (más ligero y rápido de iniciar); una VM tiene su propio kernel (mayor aislamiento, más recursos)','Las VMs son más ligeras que los contenedores Docker','Docker solo funciona en Linux; las VMs en cualquier OS'], r:1, e:'VM: hypervisor + kernel propio + SO completo = arranque en minutos, cientos de MB. Docker: comparte kernel del host, solo el proceso y sus dependencias = arranque en segundos, decenas de MB. Docker es más eficiente; la VM ofrece mayor aislamiento.' },
    { tema:'UF4', p:'¿Qué hace la instrucción EXPOSE en un Dockerfile?', ops:['Publica el puerto del contenedor en el host automáticamente','Documenta qué puertos escucha la aplicación, pero no los publica; eso lo hace -p en docker run o ports en docker-compose','Abre un puerto en el firewall del host','Define el protocolo de red del contenedor'], r:1, e:'EXPOSE 8080 es documentación: indica que la app escucha en ese puerto. No lo publica automáticamente. Para publicar: docker run -p 80:8080 imagen (host:contenedor) o en docker-compose: ports: ["80:8080"].' },
    { tema:'UF4', p:'¿Qué son las capas (layers) en una imagen Docker?', ops:['Los diferentes entornos (dev, staging, prod) de una imagen','Cada instrucción del Dockerfile crea una capa inmutable. Las capas se comparten entre imágenes para ahorrar espacio','Los diferentes puertos expuestos por la imagen','Las versiones anteriores de una imagen'], r:1, e:'Cada RUN, COPY, ADD crea una nueva capa. Las capas son inmutables y se cachean. Si solo cambia el código fuente, Docker reutiliza las capas de dependencias. Orden importa: pon lo que cambia menos al principio para aprovechar la caché.' },
    { tema:'UF4', p:'¿Qué es docker ps y qué muestra?', ops:['Lista las imágenes disponibles en el registro local','Lista los contenedores en ejecución (con -a muestra todos, incluidos los detenidos)','Muestra el uso de CPU y memoria de Docker','Muestra los logs de todos los contenedores'], r:1, e:'docker ps lista los contenedores en ejecución: ID, imagen, comando, creación, estado, puertos y nombre. docker ps -a incluye los contenedores detenidos. docker stats muestra métricas en tiempo real. docker logs nombre muestra los logs.' },
    { tema:'UF4', p:'¿Qué es un multi-stage build en Docker?', ops:['Construir la misma imagen para múltiples arquitecturas (x86, ARM)','Usar múltiples FROM en un Dockerfile para separar el entorno de compilación del de producción, resultando en imágenes más pequeñas','Construir varias imágenes en paralelo con docker-compose','Un sistema de caché avanzado para builds de Docker'], r:1, e:'Multi-stage build: primer FROM instala herramientas de compilación y genera los binarios. Segundo FROM (imagen ligera) solo copia los artefactos compilados. Resultado: imagen de producción sin compiladores ni herramientas de desarrollo (mucho más pequeña y segura).' },
    { tema:'UF4', p:'¿Qué es Kubernetes y en qué se diferencia de Docker Compose?', ops:['Kubernetes y Docker Compose son equivalentes para producción','Docker Compose es para desarrollo local (un host); Kubernetes es un orquestador para producción que gestiona contenedores en clústeres de múltiples nodos con HA, auto-scaling y self-healing','Kubernetes reemplaza completamente a Docker','Docker Compose es más escalable que Kubernetes'], r:1, e:'Docker Compose es ideal para desarrollo local y stacks simples en un servidor. Kubernetes gestiona clústeres de muchos servidores: scheduling inteligente, auto-scaling horizontal, self-healing, rolling deployments, service mesh. La curva de aprendizaje es mucho mayor.' },
    { tema:'UF4', p:'¿Qué es el .dockerignore y para qué sirve?', ops:['Un archivo que define qué usuarios pueden ejecutar Docker','Un archivo que especifica qué archivos y directorios no se incluyen en el contexto de build de Docker, similar al .gitignore','Un archivo de configuración de red de Docker','Un archivo que define qué puertos no deben exponerse'], r:1, e:'.dockerignore funciona como .gitignore pero para el build context de Docker. Excluye node_modules/, .git/, .env, logs/ del contexto enviado al daemon. Reduce el tamaño del contexto y evita incluir archivos sensibles en la imagen.' },
    { tema:'UF4', p:'¿Cuál es la señal que Docker envía primero para detener un contenedor con docker stop?', ops:['SIGKILL (termina inmediatamente)','SIGTERM (permite al proceso finalizar limpiamente), con SIGKILL como fallback tras 10s','SIGINT (equivalente a Ctrl+C)','SIGHUP (recarga de configuración)'], r:1, e:'docker stop envía SIGTERM al proceso principal, dando tiempo para cerrar conexiones y guardar estado. Si el proceso no termina en 10s (configurable), envía SIGKILL. docker kill envía directamente SIGKILL. Las apps deben manejar SIGTERM limpiamente.' },
  ],
  UF5: [
    { tema:'UF5', p:'¿Qué es un pipeline de CI/CD?', ops:['Una red de tuberías para distribución de datos entre microservicios','Una secuencia automatizada de pasos (build, test, deploy) que se ejecuta cuando hay cambios en el código, garantizando calidad y entrega continua','Un sistema de monitorización de aplicaciones','Un protocolo de comunicación entre servicios en la nube'], r:1, e:'CI (Integración Continua): cada push ejecuta automáticamente tests, análisis de código y build. CD (Entrega/Despliegue Continuo): si CI pasa, despliega automáticamente a staging o producción. Herramientas: GitHub Actions, GitLab CI, Jenkins.' },
    { tema:'UF5', p:'¿Qué es GitHub Actions?', ops:['Un servicio de hosting de código alternativo a GitHub','La plataforma de CI/CD integrada en GitHub, que automatiza workflows mediante archivos YAML en .github/workflows/','Un sistema de revisión de código automático','Una herramienta de gestión de proyectos de GitHub'], r:1, e:'GitHub Actions define workflows en YAML: on: [push] → jobs: → steps: (checkout, setup-node, npm test, deploy). Se ejecutan en runners (GitHub-hosted o self-hosted). Gratuito para repos públicos, de pago para privados.' },
    { tema:'UF5', p:'¿Qué es el despliegue continuo (CD) y en qué se diferencia de la entrega continua?', ops:['Son sinónimos, no hay diferencia','Entrega continua (CD): el código está siempre listo para desplegarse pero requiere aprobación manual. Despliegue continuo: cada cambio que pasa tests se despliega automáticamente a producción sin intervención humana.','Despliegue continuo requiere tests manuales; entrega continua los automatiza','Solo la entrega continua incluye el paso de tests'], r:1, e:'Continuous Delivery: el pipeline termina en staging listo para producción, pero un humano aprueba el deploy final. Continuous Deployment: si pasan todos los tests, el código va directamente a producción sin intervención humana. Más riesgo, más velocidad.' },
    { tema:'UF5', p:'¿Qué hace el comando git rebase y cómo difiere de git merge?', ops:['Son equivalentes, ambos integran cambios de una rama en otra','git rebase reescribe el historial moviendo commits a la punta de otra rama (historial lineal); git merge crea un commit de fusión preservando el historial de ambas ramas','git rebase es para repositorios remotos; git merge para locales','git merge es más seguro y siempre preferido sobre rebase'], r:1, e:'merge: crea un merge commit con dos padres, preserva el historial completo (más trazable). rebase: mueve los commits encima de la rama destino, reescribiendo sus hashes, creando historial lineal (más limpio pero pierde contexto temporal). Golden rule: nunca hacer rebase de ramas públicas compartidas.' },
    { tema:'UF5', p:'¿Qué es el versionado semántico (SemVer)?', ops:['Un sistema de numeración de versiones Git','El estándar MAJOR.MINOR.PATCH: MAJOR = cambios incompatibles, MINOR = nuevas funcionalidades compatibles, PATCH = correcciones de bugs','Un tipo de tag de Git para versiones de producción','Un sistema de control de versiones alternativo a Git'], r:1, e:'SemVer (semver.org): v2.3.1 → MAJOR.MINOR.PATCH. MAJOR sube cuando hay cambios incompatibles (breaking changes). MINOR para nuevas funcionalidades retrocompatibles. PATCH para correcciones de bugs. ^1.2.3 en npm acepta hasta 1.x.x.' },
    { tema:'UF5', p:'¿Qué es el staging environment en el ciclo de despliegue?', ops:['El entorno de desarrollo local de cada programador','Un entorno que replica producción donde se valida la nueva versión antes de desplegarla a usuarios reales','El entorno de producción donde están los usuarios reales','El servidor de integración continua donde se ejecutan los tests'], r:1, e:'Staging (pre-producción) es una réplica de producción: misma infraestructura, datos similares, configuración idéntica. Permite validar la versión antes del deploy final. Los QA y el cliente hacen la aceptación final aquí.' },
    { tema:'UF5', p:'¿Qué es Vercel y para qué tipo de proyectos está optimizado?', ops:['Un servicio de hosting de bases de datos','Una plataforma de despliegue automático optimizada para frontends (Next.js, React, Vue), con CDN global, preview deployments por PR y serverless functions','Un servicio de orquestación de contenedores','Un registro de paquetes npm alternativo'], r:1, e:'Vercel (creado por el equipo de Next.js) despliega frontends automáticamente en cada push. Cada PR genera un preview URL único. CDN global de más de 70 nodos. Edge Functions para lógica server-side ligera.' },
    { tema:'UF5', p:'¿Qué es Railway y en qué se diferencia de Vercel?', ops:['Son equivalentes, ambos para frontends estáticos','Railway despliega backends (Node.js, Python, PHP, bases de datos) con soporte para servicios stateful como PostgreSQL y Redis; Vercel está optimizado para frontends y serverless','Railway es solo para bases de datos en la nube','Railway es el servicio de CI/CD de GitHub'], r:1, e:'Railway despliega backends y bases de datos (PostgreSQL, Redis, MySQL) con un modelo de precios por uso. Soporta cualquier servicio que corra en Docker. Ideal para APIs, workers y bases de datos. Complementa a Vercel (frontend en Vercel, backend en Railway).' },
    { tema:'UF5', p:'¿Qué es el Infrastructure as Code (IaC)?', ops:['El código fuente de la aplicación gestionado en un repositorio','La práctica de definir y gestionar la infraestructura (servidores, redes, BD) mediante archivos de configuración versionados, reproducibles y automatizables','El código de los scripts de despliegue manual','Un sistema de monitorización basado en código'], r:1, e:'IaC (Terraform, Pulumi, CloudFormation) define la infraestructura como código versionado en Git. Permite reproducir entornos idénticos, auditar cambios en infraestructura, hacer rollback y automatizar la creación de entornos. Elimina los servidores "configurados a mano".' },
    { tema:'UF5', p:'¿Qué son los environment variables en el contexto de despliegue?', ops:['Variables que solo existen en el entorno de desarrollo local','Variables de configuración específicas de cada entorno (API keys, conexiones BD, flags) que se inyectan en la aplicación en tiempo de ejecución sin hardcodear en el código','Variables de JavaScript que se calculan en el navegador','Variables de entorno del sistema operativo del desarrollador'], r:1, e:'Las env vars (DB_URL, API_KEY, NODE_ENV) permiten el mismo código en dev/staging/prod con diferente configuración. Nunca se commitean al repositorio (.gitignore el .env). En Vercel/Railway se configuran en el panel. Siguiendo 12-factor app.' },
    { tema:'UF5', p:'¿Qué es un webhook en el contexto de CI/CD y despliegue?', ops:['Un tipo de API REST con autenticación JWT','Una petición HTTP POST que un servicio envía automáticamente a otra URL cuando ocurre un evento (push, PR, merge), disparando acciones automatizadas','Un sistema de monitorización de endpoints HTTP','Un protocolo de comunicación en tiempo real entre servidores'], r:1, e:'GitHub envía un webhook POST a Vercel/Railway/Jenkins cuando hay un push. El servicio receptor procesa el evento y dispara el pipeline. Base de la automatización CI/CD: push → webhook → build → test → deploy.' },
    { tema:'UF5', p:'¿Qué es un artefacto de build en CI/CD?', ops:['Un error o warning en el proceso de compilación','El resultado del proceso de build (binario compilado, imagen Docker, archivo .jar, bundle JS) que se guarda y usa en etapas posteriores del pipeline','Un archivo de log generado durante el CI','Una dependencia externa descargada durante el build'], r:1, e:'Los artefactos son los outputs del build: bundle.js, app.jar, imagen Docker. En GitHub Actions: actions/upload-artifact guarda artefactos entre jobs. Permiten que el job de deploy use el mismo binario que se testeó, sin recompilar.' },
  ],
};

if (typeof BANCO !== 'undefined' && typeof EXTRA_DESP !== 'undefined') {
  Object.keys(EXTRA_DESP).forEach(uf => {
    if (!BANCO[uf]) BANCO[uf] = [];
    const needed = 30 - BANCO[uf].length;
    if (needed > 0) {
      BANCO[uf] = BANCO[uf].concat(EXTRA_DESP[uf].slice(0, needed));
    }
  });
}
